/* HYPOX — content packs (original, bilingual) + AI hook
   AI HOOK: set window.HYPOX_CONFIG.aiEndpoint to a URL on your Railway backend.
   POST { mode, lang, count } -> { prompts: [...] } matching the shapes below.
   If unset or the request fails, local packs are used. */

const PACKS = {
  /* ---- BLUFF BANQUET: { fact: text with ___ , truth } ---- */
  bluff: {
    en: [
      { fact: 'In Switzerland, it is illegal to own ___', truth: 'JUST ONE GUINEA PIG (they get lonely)' },
      { fact: 'The Dubai Police supercar fleet famously includes ___', truth: 'A BUGATTI VEYRON' },
      { fact: 'Australia regularly exports ___ to Saudi Arabia', truth: 'CAMELS' },
      { fact: 'Astronauts in space temporarily become ___', truth: 'ABOUT 5CM TALLER' },
      { fact: 'Archaeologists found 3,000-year-old ___ in Egyptian tombs — still edible', truth: 'HONEY' },
      { fact: 'To make it rain more, the UAE uses ___', truth: 'CLOUD-SEEDING DRONES' },
      { fact: 'An octopus has three ___', truth: 'HEARTS' },
      { fact: 'The Eiffel Tower gets about 15cm ___ every summer', truth: 'TALLER (metal expands)' },
      { fact: 'Botanically speaking, a banana is actually ___', truth: 'A BERRY' },
      { fact: 'In Japan, a train station stayed open for years to serve ___', truth: 'ONE SINGLE STUDENT' },
      { fact: 'Scotland’s official national animal is ___', truth: 'THE UNICORN' },
      { fact: 'A single strand of spaghetti is called ___', truth: 'A SPAGHETTO' },
      { fact: 'Cleopatra lived closer in time to ___ than to the pyramids being built', truth: 'THE IPHONE' },
      { fact: 'Oxford University is older than the ___ Empire', truth: 'AZTEC' },
      { fact: 'A group of flamingos is called a ___', truth: 'FLAMBOYANCE' },
      { fact: 'The loudest animal on Earth is the ___', truth: 'SPERM WHALE' },
      { fact: 'Nintendo was originally founded in ___ as a playing card company', truth: '1889' },
      { fact: 'A group of flamingos is called a ___', truth: 'FLAMBOYANCE' },
      { fact: 'The inventor of the telephone, Alexander Graham Bell, refused to have one in his ___', truth: 'STUDY (he found it distracting)' },
      { fact: 'Cleopatra lived closer in time to ___ than to the building of the pyramids', truth: 'THE IPHONE' },
      { fact: 'Oxford University is older than ___', truth: 'THE AZTEC EMPIRE' },
      { fact: 'A day on ___ is longer than its year', truth: 'VENUS' },
      { fact: 'The inventor of Pringles was buried in a ___', truth: 'PRINGLES CAN (per his request)' },
      { fact: 'Humans share about 60% of their DNA with ___', truth: 'BANANAS' },
      { fact: 'The Twitter bird has an official name: ___', truth: 'LARRY' },
      { fact: 'Nintendo was founded in ___', truth: '1889 (as a playing card company)' },
      { fact: 'In Japan, there is a ___ specifically for people who are too tired to talk', truth: 'SILENT TAXI SERVICE' },
      { fact: 'The average person walks about ___ in a lifetime', truth: '5 TIMES AROUND THE EARTH' },
      { fact: 'A bolt of lightning is five times hotter than the ___', truth: 'SURFACE OF THE SUN' },
    ],
    ar: [
      { fact: 'في سويسرا، يمنع قانونياً امتلاك ___', truth: 'خنزير غينيا واحد فقط (لأنه يحس بالوحدة)' },
      { fact: 'أسطول شرطة دبي للسيارات الفارهة يضم ___', truth: 'بوغاتي فيرون' },
      { fact: 'أستراليا تصدّر بانتظام ___ إلى السعودية', truth: 'الجِمال' },
      { fact: 'رواد الفضاء في الفضاء يصيرون مؤقتاً ___', truth: 'أطول بحوالي ٥ سم' },
      { fact: 'علماء الآثار لقوا ___ عمرها ٣٠٠٠ سنة في مقابر مصرية — ولا زالت صالحة للأكل', truth: 'عسل' },
      { fact: 'عشان تزيد الأمطار، الإمارات تستخدم ___', truth: 'طائرات مسيّرة لتلقيح السحب' },
      { fact: 'الأخطبوط عنده ثلاثة ___', truth: 'قلوب' },
      { fact: 'برج إيفل يزيد حوالي ١٥ سم ___ كل صيف', truth: 'طولاً (المعدن يتمدد)' },
      { fact: 'نباتياً، الموز يعتبر فعلياً ___', truth: 'نوع من التوت' },
      { fact: 'في اليابان، محطة قطار ظلت شغالة سنوات عشان تخدم ___', truth: 'طالبة وحدة فقط' },
      { fact: 'الحيوان الوطني الرسمي لاسكتلندا هو ___', truth: 'وحيد القرن الخرافي (يونيكورن)' },
      { fact: 'الخيط الواحد من السباغيتي اسمه ___', truth: 'سباغيتو' },
      { fact: 'كليوباترا عاشت أقرب زمنياً لـ ___ من بناء الأهرامات', truth: 'الآيفون' },
      { fact: 'جامعة أكسفورد أقدم من الإمبراطورية ___', truth: 'الأزتيكية' },
      { fact: 'مجموعة طيور الفلامينغو تُسمى ___', truth: 'Flamboyance' },
      { fact: 'أعلى حيوان صوتاً في العالم هو ___', truth: 'الحوت الأزرق' },
      { fact: 'نينتندو أُسست في ___ كشركة أوراق لعب', truth: '١٨٨٩' },
      { fact: 'مجموعة من الفلامينغو تُسمّى ___', truth: 'فلامبويانس (Flamboyance)' },
      { fact: 'مخترع التلفون رفض وجوده في ___', truth: 'مكتبه الخاص (كان يعتبره مشتتاً)' },
      { fact: 'كليوباترا عاشت أقرب زمنياً إلى ___ من بناء الأهرامات', truth: 'الآيفون' },
      { fact: 'جامعة أكسفورد أقدم من ___', truth: 'الحضارة الأزتيكية' },
      { fact: 'اليوم على كوكب ___ أطول من سنته', truth: 'الزهرة (فينوس)' },
      { fact: 'مخترع رقائق برينغلز دُفن داخل ___', truth: 'علبة برينغلز (بوصيته)' },
      { fact: 'البشر يشتركون مع ___ في ٦٠٪ من الحمض النووي', truth: 'الموز' },
      { fact: 'طائر تويتر له اسم رسمي هو ___', truth: 'لاري (Larry)' },
      { fact: 'نينتندو تأسست عام ___ كشركة أوراق لعب', truth: '١٨٨٩' },
      { fact: 'في اليابان، هناك ___ مخصص لمن هو متعب جداً للكلام', truth: 'خدمة تاكسي صامتة' },
      { fact: 'متوسط الإنسان يمشي في حياته مسافة ___', truth: '٥ مرات حول الأرض' },
      { fact: 'برق الصاعقة أسخن بـ٥ مرات من ___', truth: 'سطح الشمس' },
    ],
  },

  /* ---- WOULD YOU RATHER PERSONAL: { a, b } (target player answers) ---- */
  wyr: {
    en: [
      { a: 'Lose your phone for a month', b: 'Lose your car for a month' },
      { a: 'Only shawarma forever', b: 'Only machboos forever' },
      { a: 'Always 30 minutes late', b: 'Always 2 hours early' },
      { a: 'Know everyone’s salary', b: 'Everyone knows YOUR salary' },
      { a: 'A Gulf summer week with no AC', b: 'A Norway winter week with no jacket' },
      { a: 'Give up coffee forever', b: 'Give up karak forever' },
      { a: 'Famous on TikTok', b: 'Rich but completely anonymous' },
      { a: 'Only communicate in voice notes', b: 'Never send a voice note again' },
      { a: 'A wedding with 2,000 guests', b: 'Elope with only 10 people' },
      { a: 'Free flights forever (middle seat only)', b: 'One business-class trip per year' },
      { a: 'Live without music', b: 'Live without series & movies' },
      { a: 'Your search history goes public', b: 'Your bank statement goes public' },
      { a: 'Win 1 million but never travel again', b: 'Travel anywhere free forever but stay broke' },
      { a: 'Always know when someone is lying to you', b: 'Get away with any lie yourself' },
      { a: 'Have a personal chef', b: 'Have a personal driver' },
      { a: 'Live in your favorite city but hate your job', b: 'Dream job but live somewhere boring' },
      { a: 'Be the funniest person in any room', b: 'Be the smartest person in any room' },
      { a: 'Know what everyone thinks of you', b: 'Never know but always wonder' },
      { a: 'Eat the same meal every day for life', b: 'Never eat your favorite food again' },
      { a: 'Be always 10 minutes early', b: 'Always 10 minutes late' },
      { a: 'Have a rewind button for life (30 sec)', b: 'A pause button (freeze time)' },
      { a: 'Live in the city forever', b: 'Live in the countryside forever' },
      { a: 'Speak every language fluently', b: 'Play every instrument perfectly' },
      { a: 'No social media for a year', b: 'No music for a year' },
      { a: 'Be famous but broke', b: 'Rich but completely unknown' },
      { a: 'Always feel cold', b: 'Always feel too hot' },
      { a: 'Read minds but only hear bad thoughts', b: 'Never know what anyone thinks' },
      { a: 'Laugh uncontrollably at funerals', b: 'Cry uncontrollably at weddings' },
      { a: 'Be the funniest person in the room', b: 'Be the smartest person in the room' },
    ],
    ar: [
      { a: 'تفقد جوالك شهر كامل', b: 'تفقد سيارتك شهر كامل' },
      { a: 'شاورما بس لبقية عمرك', b: 'مچبوس بس لبقية عمرك' },
      { a: 'دايماً متأخر نص ساعة', b: 'دايماً مبكر ساعتين' },
      { a: 'تعرف رواتب الكل', b: 'الكل يعرف راتبك أنت' },
      { a: 'أسبوع صيف خليجي بدون مكيف', b: 'أسبوع شتاء نرويجي بدون جاكيت' },
      { a: 'تترك القهوة للأبد', b: 'تترك الكرك للأبد' },
      { a: 'مشهور بتيك توك', b: 'غني بس محد يعرفك' },
      { a: 'تتواصل بس بالرسائل الصوتية', b: 'ما ترسل رسالة صوتية أبداً' },
      { a: 'عرس بـ٢٠٠٠ معزوم', b: 'زواج بس بـ١٠ أشخاص' },
      { a: 'طيران مجاني للأبد (بس كرسي النص)', b: 'رحلة درجة أعمال وحدة بالسنة' },
      { a: 'تعيش بدون موسيقى', b: 'تعيش بدون مسلسلات وأفلام' },
      { a: 'سجل بحثك يصير عام', b: 'كشف حسابك البنكي يصير عام' },
      { a: 'تكسب مليون بس ما تسافر أبداً', b: 'تسافر مجاناً كل حياتك بس بدون فلوس' },
      { a: 'تعرف دايماً لو أحد يكذب عليك', b: 'تقدر تكذب على أي أحد وما يكتشف' },
      { a: 'عندك طباخ خاص', b: 'عندك سائق خاص' },
      { a: 'مدينتك المفضلة بوظيفة تكرهها', b: 'وظيفة أحلامك بمدينة مملة' },
      { a: 'أضحك شخص في أي غرفة', b: 'أذكى شخص في أي غرفة' },
      { a: 'تعرف ما يفكر فيه الكل عنك', b: 'ما تعرف أبداً وتتساءل دائماً' },
      { a: 'تاكل نفس الوجبة كل يوم للأبد', b: 'ما تاكل طعامك المفضل أبداً' },
      { a: 'دائماً مبكر ١٠ دقايق', b: 'دائماً متأخر ١٠ دقايق' },
      { a: 'زر رجوع في الحياة (٣٠ ثانية)', b: 'زر إيقاف مؤقت (تجمّد الوقت)' },
      { a: 'تسكن المدينة للأبد', b: 'تسكن الريف للأبد' },
      { a: 'تتكلم كل لغات العالم بطلاقة', b: 'تعزف كل الآلات الموسيقية باحتراف' },
      { a: 'بدون سوشيال ميديا لسنة كاملة', b: 'بدون موسيقى لسنة كاملة' },
      { a: 'مشهور لكن مفلس', b: 'غني لكن محد يعرفك' },
      { a: 'تحس ببرد دائماً', b: 'تحس بحر دائماً' },
      { a: 'تقرأ الأفكار لكن تسمع السلبي فقط', b: 'ما تعرف ما يفكر فيه أحد أبداً' },
      { a: 'تضحك بطريقة غير مسيطر عليها في الجنازات', b: 'تبكي بطريقة غير مسيطر عليها في الأعراس' },
      { a: 'أكثر شخص مضحك في الغرفة', b: 'أكثر شخص ذكي في الغرفة' },
    ],
  },

  /* ---- THE INTERROGATION: { q } (everyone answers anonymously) ---- */
  interrogation: {
    en: [
      { q: 'What’s the most childish thing you still do?' },
      { q: 'Your go-to excuse for leaving a gathering early?' },
      { q: 'You’re invisible for one day. First thing you do?' },
      { q: 'The weirdest thing you googled recently?' },
      { q: 'Your guilty-pleasure song or artist?' },
      { q: 'If you had to marry a food, which one?' },
      { q: 'A totally useless superpower you’d still take?' },
      { q: 'The most embarrassing thing in your screenshots folder?' },
      { q: 'A job you would be absolutely terrible at?' },
      { q: 'First thing you buy with 1 million?' },
      { q: 'A habit in this friend group that secretly annoys you?' },
      { q: 'The biggest lie you told your parents as a kid?' },
      { q: 'Something you pretend to like but secretly hate?' },
      { q: 'The last time you cried and why?' },
      { q: 'A red flag in yourself you keep ignoring?' },
      { q: 'The most money you wasted on something stupid?' },
      { q: 'Something you still do that you are too old for?' },
      { q: "What's something you pretend to like but actually hate?" },
      { q: "A secret talent you have that nobody knows about?" },
      { q: "The most embarrassing thing you've done in public?" },
      { q: "Something you do when you're completely alone that you'd never admit?" },
      { q: "Your honest opinion of the most annoying person in this room?" },
      { q: "The worst lie you've told and got away with?" },
      { q: "Something you're irrationally afraid of?" },
      { q: "A phase you went through that you regret?" },
      { q: "The most childish argument you've had recently?" },
      { q: "Your actual honest opinion of your own cooking?" },
      { q: "Something you've done that you'd be embarrassed if your parents knew?" },
      { q: "The pettiest thing you've ever done for revenge?" },
    ],
    ar: [
      { q: 'شنو أكثر تصرف طفولي للحين تسويه؟' },
      { q: 'شنو عذرك الجاهز للانسحاب من القعدة بدري؟' },
      { q: 'صرت خفي ليوم واحد. أول شي بتسويه؟' },
      { q: 'أغرب شي بحثت عنه في قوقل مؤخراً؟' },
      { q: 'أغنية أو فنان تستحي تعترف إنك تسمعه؟' },
      { q: 'لو لازم تتزوج أكلة، شنو تختار؟' },
      { q: 'قوة خارقة عديمة الفايدة بس تاخذها؟' },
      { q: 'أكثر شي محرج في ملف السكرين شوت عندك؟' },
      { q: 'وظيفة بتكون فيها فاشل تماماً؟' },
      { q: 'أول شي تشتريه بمليون؟' },
      { q: 'عادة في هالشلة تزعجك بسرّية؟' },
      { q: 'أكبر كذبة كذبتها على أهلك وأنت صغير؟' },
      { q: 'شي تتظاهر إنك تحبه بس في الحقيقة تكرهه؟' },
      { q: 'آخر مرة بكيت وليش؟' },
      { q: 'علامة تحذير في نفسك تتجاهلها؟' },
      { q: 'أكثر شي أضعت عليه فلوس وكان غلط؟' },
      { q: 'شي لا زلت تسويه وأنت كبير على عمرك؟' },
      { q: 'شي تتظاهر إنك تحبه بس تكرهه في الحقيقة؟' },
      { q: 'موهبة سرية عندك ما أحد يعلم عنها؟' },
      { q: 'أكثر موقف محرج مريت فيه أمام الناس؟' },
      { q: 'شي تسويه لما تكون لحالك بالكامل ما تعترف فيه؟' },
      { q: 'رأيك الصادق عن أكثر شخص يزعجك في هذي الغرفة؟' },
      { q: 'أسوأ كذبة كذبتها وما انكشفت؟' },
      { q: 'شي تخاف منه بطريقة غير منطقية؟' },
      { q: 'مرحلة مريت فيها تندم عليها؟' },
      { q: 'أتفه خلاف صار معك مؤخراً؟' },
      { q: 'رأيك الحقيقي الصادق في طبخك؟' },
      { q: 'شي سويته تنحرج لو أهلك عرفوا فيه؟' },
      { q: 'أتفه شي سويته للانتقام من أحد؟' },
    ],
  },

  /* ---- DISS TRACK WARS: { p } (prompt about the opponent) ---- */
  diss: {
    en: [
      { p: 'Write a fake WhatsApp status for your opponent' },
      { p: 'Your opponent’s GPS voice would say…' },
      { p: 'The title of your opponent’s autobiography' },
      { p: 'What’s REALLY in your opponent’s search history' },
      { p: 'A one-star review of your opponent' },
      { p: 'Your opponent’s honest LinkedIn headline' },
      { p: 'The warning label printed on your opponent' },
      { p: 'If your opponent was an app, its description would be…' },
      { p: 'Your opponent’s secret talent nobody asked for' },
      { p: 'The ancient prophecy about your opponent' },
      { p: 'Your opponent’s villain origin story in one line' },
      { p: 'What your opponent’s phone would say in therapy' },
      { p: 'Your opponent’s Wikipedia opening line' },
      { p: 'The Netflix show about your opponent: title and description' },
      { p: 'Your opponent’s Yelp review as a human being' },
      { p: 'What your opponent’s parents really think but never say' },
      { p: 'Your opponent’s villain origin story in one sentence' },
      { p: 'Write your opponent\'s Tinder bio' },
      { p: 'A fake news headline about your opponent' },
      { p: 'Your opponent\'s villain speech in one line' },
      { p: 'TripAdvisor review of being your opponent\'s friend' },
      { p: 'Your opponent as a Netflix series: title and tagline' },
      { p: 'What your opponent\'s mom would say about their life choices' },
      { p: 'Your opponent\'s rejected Olympic sport' },
      { p: 'Your opponent\'s dating profile red flags' },
      { p: 'Loading screen tip if your opponent was a video game' },
      { p: 'A motivational quote but about your opponent\'s failures' },
    ],
    ar: [
      { p: 'اكتب حالة واتساب مزيفة لخصمك' },
      { p: '…صوت الملاحة (GPS) عند خصمك بيقول' },
      { p: 'عنوان السيرة الذاتية لخصمك' },
      { p: 'شنو فعلياً في سجل بحث خصمك' },
      { p: 'تقييم نجمة وحدة لخصمك' },
      { p: 'عنوان LinkedIn الصادق لخصمك' },
      { p: 'ملصق التحذير المطبوع على خصمك' },
      { p: '…لو خصمك تطبيق، وصفه بيكون' },
      { p: 'موهبة خصمك السرية اللي محد طلبها' },
      { p: 'النبوءة القديمة عن خصمك' },
      { p: 'قصة تحول خصمك لشرير — بسطر واحد' },
      { p: 'شنو بيقول جوال خصمك عند الطبيب النفسي' },
      { p: 'السطر الأول في ويكيبيديا عن خصمك' },
      { p: 'خصمك كمسلسل نتفليكس: الاسم والوصف' },
      { p: 'تقييم خصمك كإنسان على قوقل' },
      { p: 'شنو أهل خصمك يفكرون فيه بسرّية' },
      { p: 'قصة تحول خصمك لشرير بجملة وحدة' },
      { p: 'اكتب بايو تيندر لخصمك' },
      { p: 'عنوان خبر عاجل زائف عن خصمك' },
      { p: 'خطاب الشرير لخصمك بسطر واحد' },
      { p: 'تقييم TripAdvisor عن الصداقة مع خصمك' },
      { p: 'خصمك كمسلسل نتفليكس: الاسم والوصف' },
      { p: 'شنو أم خصمك بتقول عن اختياراته في الحياة؟' },
      { p: 'الرياضة الأولمبية المرفوضة المناسبة لخصمك' },
      { p: 'علامات التحذير في بروفايل المواعدة لخصمك' },
      { p: 'نصيحة شاشة التحميل لو خصمك كان لعبة فيديو' },
      { p: 'جملة تحفيزية لكنها عن إخفاقات خصمك' },
    ],
  },

  /* ---- MAJLIS QUIZ: { q, options[4], correct(index) } ---- */
  quiz: {
    en: [
      { q: 'Which country has the most islands in the world?', options: ['Indonesia', 'Sweden', 'Philippines', 'Greece'], correct: 1 },
      { q: 'What is the national animal of Oman?', options: ['Falcon', 'Arabian Horse', 'Arabian Oryx', 'Camel'], correct: 2 },
      { q: 'How many strings does a classic oud usually have?', options: ['6', '8', '11', '12'], correct: 2 },
      { q: 'Which planet has the most moons?', options: ['Jupiter', 'Saturn', 'Neptune', 'Mars'], correct: 1 },
      { q: 'The capital of Australia is…', options: ['Sydney', 'Melbourne', 'Canberra', 'Perth'], correct: 2 },
      { q: 'Which sea has no coastline at all?', options: ['Dead Sea', 'Sargasso Sea', 'Caspian Sea', 'Coral Sea'], correct: 1 },
      { q: 'The first Arab country to play in a FIFA World Cup?', options: ['Morocco', 'Saudi Arabia', 'Egypt', 'Tunisia'], correct: 2 },
      { q: 'Omani cuisine is famous for which dried ingredient?', options: ['Dried lime (loomi)', 'Dried figs', 'Dried mint', 'Dried mango'], correct: 0 },
      { q: 'What does “www” stand for?', options: ['World Wide Web', 'Web World Wide', 'Wide World Web', 'World Web Wire'], correct: 0 },
      { q: 'The fastest land animal is…', options: ['Gazelle', 'Cheetah', 'Greyhound', 'Ostrich'], correct: 1 },
      { q: 'Which of these is botanically a berry?', options: ['Strawberry', 'Raspberry', 'Banana', 'Blackberry'], correct: 2 },
      { q: 'The tallest building in the world is in…', options: ['Riyadh', 'Shanghai', 'Dubai', 'Kuala Lumpur'], correct: 2 },
      { q: 'How many bones are in the human body?', options: ['186', '206', '226', '246'], correct: 1 },
      { q: 'Which planet is closest to the Sun?', options: ['Venus', 'Mercury', 'Mars', 'Earth'], correct: 1 },
      { q: 'Most spoken language by native speakers?', options: ['English', 'Spanish', 'Hindi', 'Mandarin'], correct: 3 },
      { q: 'Which country invented pizza?', options: ['France', 'Greece', 'Italy', 'Spain'], correct: 2 },
      { q: 'How many sides does a hexagon have?', options: ['5', '6', '7', '8'], correct: 1 },
      { q: 'Longest bone in the human body?', options: ['Spine', 'Femur', 'Tibia', 'Humerus'], correct: 1 },
      { q: 'Which ocean is the largest?', options: ['Atlantic', 'Indian', 'Arctic', 'Pacific'], correct: 3 },
      { q: 'WWII ended in which year?', options: ['1943', '1944', '1945', '1946'], correct: 2 },
      { q: 'Standard guitar has how many strings?', options: ['4', '5', '6', '7'], correct: 2 },
      { q: 'Element with symbol "Au" is…', options: ['Silver', 'Copper', 'Gold', 'Aluminum'], correct: 2 },
      { q: 'Smallest country in the world?', options: ['Monaco', 'San Marino', 'Vatican City', 'Liechtenstein'], correct: 2 },
      { q: 'Which continent has the most countries?', options: ['Asia', 'Europe', 'Africa', 'Americas'], correct: 2 },
    ],
    ar: [
      { q: 'أي دولة عندها أكبر عدد جزر في العالم؟', options: ['إندونيسيا', 'السويد', 'الفلبين', 'اليونان'], correct: 1 },
      { q: 'شنو الحيوان الوطني لسلطنة عُمان؟', options: ['الصقر', 'الحصان العربي', 'المها العربي', 'الجمل'], correct: 2 },
      { q: 'كم وتر عادةً في العود الكلاسيكي؟', options: ['٦', '٨', '١١', '١٢'], correct: 2 },
      { q: 'أي كوكب عنده أكبر عدد أقمار؟', options: ['المشتري', 'زحل', 'نبتون', 'المريخ'], correct: 1 },
      { q: '…عاصمة أستراليا هي', options: ['سيدني', 'ملبورن', 'كانبرا', 'بيرث'], correct: 2 },
      { q: 'أي بحر ما عنده أي سواحل؟', options: ['البحر الميت', 'بحر سارجاسو', 'بحر قزوين', 'البحر المرجاني'], correct: 1 },
      { q: 'أول دولة عربية تشارك في كأس العالم؟', options: ['المغرب', 'السعودية', 'مصر', 'تونس'], correct: 2 },
      { q: 'المطبخ العماني مشهور بأي مكوّن مجفف؟', options: ['اللومي (الليمون المجفف)', 'التين المجفف', 'النعناع المجفف', 'المانجو المجفف'], correct: 0 },
      { q: 'شنو معنى «www»؟', options: ['World Wide Web', 'Web World Wide', 'Wide World Web', 'World Web Wire'], correct: 0 },
      { q: '…أسرع حيوان بري هو', options: ['الغزال', 'الفهد', 'كلب السلوقي', 'النعامة'], correct: 1 },
      { q: 'أي واحد من هذي يعتبر نباتياً من التوتيات؟', options: ['الفراولة', 'التوت الأحمر', 'الموز', 'التوت الأسود'], correct: 2 },
      { q: '…أطول برج في العالم موجود في', options: ['الرياض', 'شنغهاي', 'دبي', 'كوالالمبور'], correct: 2 },
      { q: 'كم عدد عظام جسم الإنسان؟', options: ['١٨٦', '٢٠٦', '٢٢٦', '٢٤٦'], correct: 1 },
      { q: 'أي كوكب الأقرب للشمس؟', options: ['الزهرة', 'عطارد', 'المريخ', 'الأرض'], correct: 1 },
      { q: 'أكثر لغة متحدث بها كلغة أم في العالم؟', options: ['الإنجليزية', 'الإسبانية', 'الهندية', 'الماندرين'], correct: 3 },
      { q: 'أي دولة اخترعت البيتزا؟', options: ['فرنسا', 'اليونان', 'إيطاليا', 'إسبانيا'], correct: 2 },
      { q: 'كم ضلعاً في السداسي؟', options: ['٥', '٦', '٧', '٨'], correct: 1 },
      { q: 'أطول عظمة في جسم الإنسان؟', options: ['العمود الفقري', 'عظمة الفخذ', 'الساق', 'العضد'], correct: 1 },
      { q: 'أي محيط هو الأكبر؟', options: ['الأطلسي', 'الهندي', 'المتجمد الشمالي', 'الهادي'], correct: 3 },
      { q: 'في أي سنة انتهت الحرب العالمية الثانية؟', options: ['١٩٤٣', '١٩٤٤', '١٩٤٥', '١٩٤٦'], correct: 2 },
      { q: 'كم وتراً في الغيتار العادي؟', options: ['٤', '٥', '٦', '٧'], correct: 2 },
      { q: 'عنصر رمزه Au هو؟', options: ['الفضة', 'النحاس', 'الذهب', 'الألومنيوم'], correct: 2 },
      { q: 'أصغر دولة في العالم؟', options: ['موناكو', 'سان مارينو', 'الفاتيكان', 'ليختنشتاين'], correct: 2 },
      { q: 'أي قارة فيها أكثر عدد من الدول؟', options: ['آسيا', 'أوروبا', 'أفريقيا', 'الأمريكتين'], correct: 2 },
    ],
  },
};

const Content = {
  /* Async so an AI backend can be swapped in with zero changes elsewhere.
     region: 'mena' | 'weur' | 'asia' | 'africa' | null (null = universal only) */
  async get(mode, lang, count, region) {
    // Arab Flavor = use MENA regional pack first; Global Mix = no regional preference
    if (!region) {
      const flavor = window.HYPOX_STATE && window.HYPOX_STATE.flavor;
      region = (flavor === 'arab') ? 'mena' : null;
    }
    const cfg = window.HYPOX_CONFIG || {};
    if (cfg.aiEndpoint) {
      try {
        const res = await fetch(cfg.aiEndpoint, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ mode, lang, count, region }),
        });
        if (res.ok) {
          const data = await res.json();
          if (Array.isArray(data.prompts) && data.prompts.length) return data.prompts.slice(0, count);
        }
      } catch (e) { /* fall through to local packs */ }
    }

    // Guard: nothing to fetch
    if (count <= 0) return [];

    // Warn host if static pool is smaller than requested (content will repeat)
    const poolSize = ((PACKS[mode] && (PACKS[mode][lang] || PACKS[mode].en)) || []).length;
    if (poolSize > 0 && count > poolSize) {
      const toast = document.createElement('div');
      toast.style.cssText = 'position:fixed;bottom:4vmin;left:50%;transform:translateX(-50%);background:#374151;color:#facc15;font-family:Fredoka One,sans-serif;font-size:15px;padding:10px 22px;border-radius:50px;z-index:99;opacity:0.92;pointer-events:none';
      toast.textContent = '🔄 Content repeating — AI backend will fix this';
      document.body.appendChild(toast);
      setTimeout(() => toast.remove(), 3500);
    }



    // Universal pool (always available)
    const universal = (PACKS[mode] && (PACKS[mode][lang] || PACKS[mode].en)) || [];

    // Regional pool for location-sensitive modes (quiz/bluff), if a region is set
    let regional = [];
    if (region && typeof REGION_PACKS !== 'undefined' && REGION_PACKS[region] && REGION_PACKS[region][mode]) {
      regional = REGION_PACKS[region][mode][lang] || REGION_PACKS[region][mode].en || [];
    }

    // Prefer regional first (feels local), then top up from universal so variety stays high.
    const merged = [...shuffle(regional), ...shuffle(universal)];
    // De-dupe by full content
    const seen = new Set(), out = [];
    for (const item of merged) {
      if (out.length >= count) break;
      const key = JSON.stringify(item);
      if (seen.has(key)) continue;
      seen.add(key); out.push(item);
    }
    return out.length ? out : shuffle(universal).slice(0, count);
  },
};

/* ============ TRIVIA CATEGORIES ============
   Used by the "Speed Trivia" mode when a category is selected.
   Each has 12 questions in EN and AR. */
const TRIVIA_CATS = {
  geography: {
    en: [
      { q:'What is the capital of Australia?', options:['Sydney','Melbourne','Canberra','Perth'], correct:2 },
      { q:'Which country has the most natural lakes?', options:['USA','Russia','Canada','Brazil'], correct:2 },
      { q:'The Nile River flows through how many countries?', options:['7','9','11','13'], correct:2 },
      { q:'Which ocean is the largest?', options:['Atlantic','Indian','Arctic','Pacific'], correct:3 },
      { q:'Mount Everest is in which mountain range?', options:['Andes','Alps','Himalayas','Rockies'], correct:2 },
      { q:'What is the smallest country in the world?', options:['Monaco','San Marino','Liechtenstein','Vatican City'], correct:3 },
      { q:'The Amazon River is in which continent?', options:['Africa','Asia','South America','North America'], correct:2 },
      { q:'Which city is both in Europe and Asia?', options:['Moscow','Istanbul','Cairo','Athens'], correct:1 },
      { q:'What is the longest river in the Arab world?', options:['Euphrates','Tigris','Nile','Jordan'], correct:2 },
      { q:'Which country has the most pyramids?', options:['Egypt','Sudan','Mexico','Peru'], correct:1 },
      { q:'The Sahara Desert covers most of which continent?', options:['Asia','Africa','Australia','South America'], correct:1 },
      { q:'Which Gulf country has no river?', options:['Iraq','Kuwait','Oman','Jordan'], correct:1 },
    ],
    ar: [
      { q:'ما عاصمة أستراليا؟', options:['سيدني','ملبورن','كانبرا','بيرث'], correct:2 },
      { q:'أي دولة عندها أكبر عدد بحيرات طبيعية؟', options:['أمريكا','روسيا','كندا','البرازيل'], correct:2 },
      { q:'نهر النيل يمر عبر كم دولة؟', options:['٧','٩','١١','١٣'], correct:2 },
      { q:'أكبر محيط في العالم؟', options:['الأطلسي','الهندي','المتجمد','الهادئ'], correct:3 },
      { q:'جبل إيفرست في أي سلسلة جبلية؟', options:['الأنديز','الألب','الهيمالايا','الروكي'], correct:2 },
      { q:'أصغر دولة في العالم؟', options:['موناكو','سان مارينو','ليختنشتاين','الفاتيكان'], correct:3 },
      { q:'نهر الأمازون في أي قارة؟', options:['أفريقيا','آسيا','أمريكا الجنوبية','أمريكا الشمالية'], correct:2 },
      { q:'أي مدينة في أوروبا وآسيا معاً؟', options:['موسكو','إسطنبول','القاهرة','أثينا'], correct:1 },
      { q:'أطول نهر في العالم العربي؟', options:['الفرات','دجلة','النيل','الأردن'], correct:2 },
      { q:'أي دولة عندها أكبر عدد أهرامات؟', options:['مصر','السودان','المكسيك','بيرو'], correct:1 },
      { q:'الصحراء الكبرى تغطي معظم أي قارة؟', options:['آسيا','أفريقيا','أستراليا','أمريكا'], correct:1 },
      { q:'أي دولة خليجية ليس فيها أنهار؟', options:['العراق','الكويت','عُمان','الأردن'], correct:1 },
    ],
  },
  science: {
    en: [
      { q:'What is the chemical symbol for gold?', options:['Go','Gd','Au','Ag'], correct:2 },
      { q:'How many bones are in the adult human body?', options:['196','206','216','226'], correct:1 },
      { q:'What planet is known as the Red Planet?', options:['Venus','Jupiter','Saturn','Mars'], correct:3 },
      { q:'What is the speed of light (approx)?', options:['200,000 km/s','300,000 km/s','400,000 km/s','500,000 km/s'], correct:1 },
      { q:'DNA stands for?', options:['Deoxyribonucleic Acid','Dioxynuclear Acid','Double Nucleic Arrangement','Digital Nucleic Acid'], correct:0 },
      { q:'What is the hardest natural substance?', options:['Gold','Iron','Diamond','Quartz'], correct:2 },
      { q:'Which gas do plants absorb from the air?', options:['Oxygen','Nitrogen','Carbon Dioxide','Hydrogen'], correct:2 },
      { q:'How many hearts does an octopus have?', options:['1','2','3','4'], correct:2 },
      { q:'What is the powerhouse of the cell?', options:['Nucleus','Ribosome','Mitochondria','Golgi body'], correct:2 },
      { q:'Water boils at what temperature at sea level?', options:['90°C','95°C','100°C','105°C'], correct:2 },
      { q:'Which planet has the most moons?', options:['Jupiter','Saturn','Neptune','Uranus'], correct:1 },
      { q:'What is the most abundant gas in Earth\'s atmosphere?', options:['Oxygen','Argon','Carbon Dioxide','Nitrogen'], correct:3 },
    ],
    ar: [
      { q:'ما الرمز الكيميائي للذهب؟', options:['Go','Gd','Au','Ag'], correct:2 },
      { q:'كم عظمة في جسم الإنسان البالغ؟', options:['١٩٦','٢٠٦','٢١٦','٢٢٦'], correct:1 },
      { q:'أي كوكب يُعرف بالكوكب الأحمر؟', options:['الزهرة','المشتري','زحل','المريخ'], correct:3 },
      { q:'ما سرعة الضوء تقريباً؟', options:['٢٠٠ ألف كم/ث','٣٠٠ ألف كم/ث','٤٠٠ ألف كم/ث','٥٠٠ ألف كم/ث'], correct:1 },
      { q:'DNA اختصار لـ؟', options:['حمض الديوكسي ريبونيوكليك','حمض نووي مزدوج','حمض نيتروجيني','حمض ريبوزي'], correct:0 },
      { q:'أصلب مادة طبيعية؟', options:['الذهب','الحديد','الماس','الكوارتز'], correct:2 },
      { q:'أي غاز تمتصه النباتات من الهواء؟', options:['الأكسجين','النيتروجين','ثاني أكسيد الكربون','الهيدروجين'], correct:2 },
      { q:'كم قلب عند الأخطبوط؟', options:['١','٢','٣','٤'], correct:2 },
      { q:'محطة الطاقة في الخلية؟', options:['النواة','الريبوسوم','الميتوكوندريا','جهاز غولجي'], correct:2 },
      { q:'الماء يغلي على كم درجة عند مستوى البحر؟', options:['٩٠','٩٥','١٠٠','١٠٥'], correct:2 },
      { q:'أي كوكب عنده أكثر أقمار؟', options:['المشتري','زحل','نبتون','أورانوس'], correct:1 },
      { q:'أكثر غاز في الغلاف الجوي للأرض؟', options:['الأكسجين','الأرغون','ثاني أكسيد الكربون','النيتروجين'], correct:3 },
    ],
  },
  gulf: {
    en: [
      { q:'What is the tallest building in the world?', options:['Burj Al Arab','Kingdom Tower','Burj Khalifa','ADNOC HQ'], correct:2 },
      { q:'Which Gulf country produces the most oil?', options:['UAE','Kuwait','Qatar','Saudi Arabia'], correct:3 },
      { q:'What is the national dish of Saudi Arabia?', options:['Kabsa','Harees','Mandi','Jareesh'], correct:0 },
      { q:'The GCC was founded in which year?', options:['1975','1981','1985','1990'], correct:1 },
      { q:'Which emirate in the UAE is the largest by area?', options:['Dubai','Sharjah','Abu Dhabi','Ras Al Khaimah'], correct:2 },
      { q:'What does "Wasta" mean in Gulf culture?', options:['A type of food','Using connections/influence','A traditional dance','A form of greeting'], correct:1 },
      { q:'The Pearl Roundabout was in which country?', options:['Kuwait','Bahrain','Qatar','UAE'], correct:1 },
      { q:'Which country has the tallest flagpole in the Arab world?', options:['Saudi Arabia','Jordan','Egypt','UAE'], correct:1 },
      { q:'Karak tea is most associated with which country?', options:['India','Pakistan','Kuwait','Qatar'], correct:2 },
      { q:'What is the official currency of Oman?', options:['Dirham','Riyal','Dinar','Dollar'], correct:1 },
      { q:'Which Gulf city is known as the "City of Gold"?', options:['Riyadh','Abu Dhabi','Dubai','Doha'], correct:2 },
      { q:'What sport is the UAE\'s national sport?', options:['Football','Camel Racing','Falconry','Horse Racing'], correct:2 },
    ],
    ar: [
      { q:'أطول مبنى في العالم؟', options:['برج العرب','برج المملكة','برج خليفة','مقر أدنوك'], correct:2 },
      { q:'أي دولة خليجية تنتج أكثر نفط؟', options:['الإمارات','الكويت','قطر','السعودية'], correct:3 },
      { q:'الطبق الوطني للسعودية؟', options:['الكبسة','الهريس','المندي','الجريش'], correct:0 },
      { q:'مجلس التعاون الخليجي أُسس في أي سنة؟', options:['١٩٧٥','١٩٨١','١٩٨٥','١٩٩٠'], correct:1 },
      { q:'أكبر إمارة في الإمارات مساحةً؟', options:['دبي','الشارقة','أبوظبي','رأس الخيمة'], correct:2 },
      { q:'معنى "الواسطة" في الثقافة الخليجية؟', options:['نوع أكل','استخدام العلاقات','رقصة تراثية','طريقة تحية'], correct:1 },
      { q:'دوار اللؤلؤة كان في أي دولة؟', options:['الكويت','البحرين','قطر','الإمارات'], correct:1 },
      { q:'أطول سارية علم في العالم العربي؟', options:['السعودية','الأردن','مصر','الإمارات'], correct:1 },
      { q:'شاي الكرك مرتبط أكثر بأي دولة؟', options:['الهند','باكستان','الكويت','قطر'], correct:2 },
      { q:'عملة سلطنة عُمان الرسمية؟', options:['الدرهم','الريال','الدينار','الدولار'], correct:1 },
      { q:'أي مدينة خليجية تُعرف بـ"مدينة الذهب"؟', options:['الرياض','أبوظبي','دبي','الدوحة'], correct:2 },
      { q:'الرياضة الوطنية للإمارات؟', options:['الكرة','سباق الجِمال','الصيد بالصقر','سباق الخيل'], correct:2 },
    ],
  },
  pop: {
    en: [
      { q:'Which app has the most monthly active users?', options:['Instagram','TikTok','YouTube','WhatsApp'], correct:3 },
      { q:'Who sang "Shape of You"?', options:['Justin Bieber','Bruno Mars','Ed Sheeran','Harry Styles'], correct:2 },
      { q:'Netflix was founded in which year?', options:['1997','1999','2001','2003'], correct:0 },
      { q:'What does "LOL" stand for?', options:['Lots of Love','Laugh Out Loud','League of Legends','All of the above'], correct:3 },
      { q:'Which country produces the most movies per year?', options:['USA','Nigeria','India','China'], correct:2 },
      { q:'The iPhone was first released in?', options:['2005','2006','2007','2008'], correct:2 },
      { q:'Who is the most followed person on Instagram?', options:['Cristiano Ronaldo','Kylie Jenner','Selena Gomez','Leo Messi'], correct:0 },
      { q:'Which game has the most players ever?', options:['Fortnite','Minecraft','PUBG','GTA V'], correct:1 },
      { q:'What is the most streamed song on Spotify ever?', options:['Blinding Lights','Shape of You','Bohemian Rhapsody','Despacito'], correct:0 },
      { q:'TikTok is owned by which company?', options:['Tencent','Alibaba','ByteDance','Baidu'], correct:2 },
      { q:'Which show has the most Emmy wins?', options:['Breaking Bad','Game of Thrones','The Wire','Succession'], correct:1 },
      { q:'What year did COVID-19 officially become a pandemic?', options:['2019','2020','2021','2022'], correct:1 },
    ],
    ar: [
      { q:'أي تطبيق عنده أكثر مستخدمين شهرياً؟', options:['انستقرام','تيك توك','يوتيوب','واتساب'], correct:3 },
      { q:'منو غنى "Shape of You"؟', options:['جاستن بيبر','برونو مارس','إد شيران','هاري ستايلز'], correct:2 },
      { q:'نتفليكس أُسست في أي سنة؟', options:['١٩٩٧','١٩٩٩','٢٠٠١','٢٠٠٣'], correct:0 },
      { q:'شنو معنى "LOL"؟', options:['كثير من الحب','اضحك بصوت عالي','ليغ أوف ليجندز','كل ما سبق'], correct:3 },
      { q:'أي دولة تنتج أكثر أفلام سنوياً؟', options:['أمريكا','نيجيريا','الهند','الصين'], correct:2 },
      { q:'أول آيفون نزل في؟', options:['٢٠٠٥','٢٠٠٦','٢٠٠٧','٢٠٠٨'], correct:2 },
      { q:'أكثر شخص متابَع على انستقرام؟', options:['رونالدو','كايلي جينر','سيلينا غوميز','ميسي'], correct:0 },
      { q:'أي لعبة عندها أكثر لاعبين؟', options:['فورتنايت','ماينكرافت','ببجي','GTA V'], correct:1 },
      { q:'أكثر أغنية استمعت على سبوتيفاي؟', options:['Blinding Lights','Shape of You','Bohemian Rhapsody','Despacito'], correct:0 },
      { q:'تيك توك ملك أي شركة؟', options:['تينسنت','علي بابا','بايت دانس','بايدو'], correct:2 },
      { q:'أي مسلسل ربح أكثر جائزة إيمي؟', options:['Breaking Bad','Game of Thrones','The Wire','Succession'], correct:1 },
      { q:'كوفيد-١٩ أصبح رسمياً وباءً في أي سنة؟', options:['٢٠١٩','٢٠٢٠','٢٠٢١','٢٠٢٢'], correct:1 },
    ],
  },
  sports: {
    en: [
      { q:'How many players are on a football (soccer) team?', options:['9','10','11','12'], correct:2 },
      { q:'Which country has won the most FIFA World Cups?', options:['Germany','Argentina','Italy','Brazil'], correct:3 },
      { q:'The 2022 World Cup was held in?', options:['UAE','Saudi Arabia','Qatar','Kuwait'], correct:2 },
      { q:'How many Grand Slam tournaments are in tennis?', options:['2','3','4','5'], correct:2 },
      { q:'Michael Jordan played for which NBA team?', options:['Lakers','Celtics','Bulls','Heat'], correct:2 },
      { q:'How many rings are on the Olympic flag?', options:['4','5','6','7'], correct:1 },
      { q:'Which country invented football (soccer)?', options:['Brazil','Spain','England','Italy'], correct:2 },
      { q:'How long is a standard marathon?', options:['40km','42.195km','44km','45km'], correct:1 },
      { q:'In which sport do you use a shuttlecock?', options:['Tennis','Squash','Badminton','Racquetball'], correct:2 },
      { q:'Cristiano Ronaldo plays for which country?', options:['Spain','Brazil','Portugal','Italy'], correct:2 },
      { q:'Which city hosted the 2024 Summer Olympics?', options:['Los Angeles','Tokyo','London','Paris'], correct:3 },
      { q:'How many players are on a basketball team on court?', options:['4','5','6','7'], correct:1 },
    ],
    ar: [
      { q:'كم لاعب في فريق كرة القدم؟', options:['٩','١٠','١١','١٢'], correct:2 },
      { q:'أي دولة فازت بأكثر كؤوس عالم؟', options:['ألمانيا','الأرجنتين','إيطاليا','البرازيل'], correct:3 },
      { q:'كأس العالم ٢٠٢٢ انعقد في؟', options:['الإمارات','السعودية','قطر','الكويت'], correct:2 },
      { q:'كم بطولة غراند سلام في التنس؟', options:['٢','٣','٤','٥'], correct:2 },
      { q:'مايكل جوردان لعب مع أي فريق NBA؟', options:['ليكرز','سيلتيكس','بولز','هيت'], correct:2 },
      { q:'كم حلقة على علم الأولمبياد؟', options:['٤','٥','٦','٧'], correct:1 },
      { q:'أي دولة اخترعت كرة القدم؟', options:['البرازيل','إسبانيا','إنجلترا','إيطاليا'], correct:2 },
      { q:'طول سباق الماراثون القياسي؟', options:['٤٠كم','٤٢.١٩٥كم','٤٤كم','٤٥كم'], correct:1 },
      { q:'في أي رياضة تستخدم الريشة؟', options:['التنس','السكواش','البادمنتون','الراكيتبول'], correct:2 },
      { q:'رونالدو يلعب لأي منتخب؟', options:['إسبانيا','البرازيل','البرتغال','إيطاليا'], correct:2 },
      { q:'أي مدينة استضافت أولمبياد صيف ٢٠٢٤؟', options:['لوس أنجلوس','طوكيو','لندن','باريس'], correct:3 },
      { q:'كم لاعب في الملعب في كرة السلة؟', options:['٤','٥','٦','٧'], correct:1 },
    ],
  },
};

/* ============ PINPOINT — geography guessing (PinWorld style) ============ */
const PINPOINT_CITIES = [
  { en:'Dubai', ar:'دبي', lat:25.2, lon:55.3 },
  { en:'Paris', ar:'باريس', lat:48.9, lon:2.35 },
  { en:'Tokyo', ar:'طوكيو', lat:35.7, lon:139.7 },
  { en:'New York', ar:'نيويورك', lat:40.7, lon:-74.0 },
  { en:'Cairo', ar:'القاهرة', lat:30.0, lon:31.2 },
  { en:'London', ar:'لندن', lat:51.5, lon:-0.13 },
  { en:'Muscat', ar:'مسقط', lat:23.6, lon:58.5 },
  { en:'Rio de Janeiro', ar:'ريو دي جانيرو', lat:-22.9, lon:-43.2 },
  { en:'Sydney', ar:'سيدني', lat:-33.9, lon:151.2 },
  { en:'Moscow', ar:'موسكو', lat:55.8, lon:37.6 },
  { en:'Cape Town', ar:'كيب تاون', lat:-33.9, lon:18.4 },
  { en:'Mumbai', ar:'مومباي', lat:19.1, lon:72.9 },
  { en:'Istanbul', ar:'إسطنبول', lat:41.0, lon:29.0 },
  { en:'Mexico City', ar:'مكسيكو سيتي', lat:19.4, lon:-99.1 },
  { en:'Riyadh', ar:'الرياض', lat:24.7, lon:46.7 },
  { en:'Singapore', ar:'سنغافورة', lat:1.35, lon:103.8 },
  { en:'Reykjavik', ar:'ريكيافيك', lat:64.1, lon:-21.9 },
  { en:'Nairobi', ar:'نيروبي', lat:-1.3, lon:36.8 },
  { en:'Buenos Aires', ar:'بوينس آيرس', lat:-34.6, lon:-58.4 },
  { en:'Seoul', ar:'سيول', lat:37.6, lon:127.0 },
  { en:'Doha', ar:'الدوحة', lat:25.3, lon:51.5 },
  { en:'Los Angeles', ar:'لوس أنجلوس', lat:34.05, lon:-118.2 },
  { en:'Rome', ar:'روما', lat:41.9, lon:12.5 },
  { en:'Bangkok', ar:'بانكوك', lat:13.75, lon:100.5 },
];

/* ===== EMOJI RIDDLE pack ===== */
PACKS.emoji = {
  en: [
    { answer:'SEOUL', category:'City', e:'🌊🦉', parts:['sea','owl'], explanation:'Sea + owl = Seoul' },
    { answer:'IRAN', category:'Country', e:'👁️🏃', parts:['eye','ran'], explanation:'Eye + ran = Iran' },
    { answer:'OMAN', category:'Country', e:'🅾️👨', parts:['o','man'], explanation:'O + man = Oman' },
    { answer:'BELIEF', category:'Word', e:'🐝🍃', parts:['bee','leaf'], explanation:'Bee + leaf = Belief' },
    { answer:'CARPET', category:'Object', e:'🚗🐾', parts:['car','pet'], explanation:'Car + pet = Carpet' },
    { answer:'BASKET', category:'Object', e:'🧺🎾', parts:['bas','ket'], explanation:'Bas + ket = Basket' },
    { answer:'WALLET', category:'Object', e:'🦭🦶', parts:['wal','let'], explanation:'Wal + let = Wallet' },
    { answer:'BUTTER', category:'Food', e:'🦋🐛', parts:['butt','er'], explanation:'Butt + er = Butter' },
    { answer:'TURKEY', category:'Country', e:'2️⃣🔑', parts:['tur','key'], explanation:'Tur + key = Turkey' },
    { answer:'JACKET', category:'Clothing', e:'🃏🏑', parts:['jack','et'], explanation:'Jack + et = Jacket' },
    { answer:'ROCKET', category:'Object', e:'🪨🎾', parts:['rock','et'], explanation:'Rock + et = Rocket' },
    { answer:'PLANET', category:'Space', e:'🍺🔩', parts:['plan','et'], explanation:'Plan + et = Planet' },
    { answer:'SOCKET', category:'Object', e:'🧦🎾', parts:['sock','et'], explanation:'Sock + et = Socket' },
    { answer:'BULLET', category:'Object', e:'🐂🍃', parts:['bull','et'], explanation:'Bull + et = Bullet' },
    { answer:'HAMLET', category:'Play', e:'🐷🍖', parts:['ham','let'], explanation:'Ham + let = Hamlet' },
    { answer:'BUCKET', category:'Object', e:'🦌🎾', parts:['buck','et'], explanation:'Buck + et = Bucket' },
    { answer:'CRICKET', category:'Sport', e:'🦗🎾', parts:['crick','et'], explanation:'Crick + et = Cricket' },
    { answer:'MARKET', category:'Place', e:'🔱🎾', parts:['mar','ket'], explanation:'Mar + ket = Market' },
    { answer:'BLANKET', category:'Object', e:'⚫🔩🎾', parts:['blank','et'], explanation:'Blank + et = Blanket' },
    { answer:'ISLAND', category:'Place', e:'👁️🏝️', parts:['eye','land'], explanation:'Eye + land = Island' },
  ],
  ar: [
    { answer:'سيول', category:'مدينة', e:'🌊🦉', parts:['sea','owl'], explanation:'Sea + owl = Seoul' },
    { answer:'إيران', category:'دولة', e:'👁️🏃', parts:['eye','ran'], explanation:'Eye + ran = Iran' },
    { answer:'عُمان', category:'دولة', e:'🅾️👨', parts:['o','man'], explanation:'O + man = Oman' },
    { answer:'تركيا', category:'دولة', e:'2️⃣🔑', parts:['tur','key'], explanation:'Tur + key = Turkey' },
    { answer:'كاربيت', category:'شيء', e:'🚗🐾', parts:['car','pet'], explanation:'Car + pet = Carpet' },
    { answer:'باسكيت', category:'رياضة', e:'🧺🎾', parts:['bas','ket'], explanation:'Bas + ket = Basket' },
    { answer:'جاكيت', category:'ملابس', e:'🃏🏑', parts:['jack','et'], explanation:'Jack + et = Jacket' },
    { answer:'روكيت', category:'شيء', e:'🪨🎾', parts:['rock','et'], explanation:'Rock + et = Rocket' },
    { answer:'ماركيت', category:'مكان', e:'🔱🎾', parts:['mar','ket'], explanation:'Mar + ket = Market' },
    { answer:'بلانكيت', category:'شيء', e:'⚫🔩🎾', parts:['blank','et'], explanation:'Blank + et = Blanket' },
  ],
};

/* ===== PINPOINT/* ===== PINPOINT landmarks with photos (Wikimedia) ===== */
const WM = f => 'https://commons.wikimedia.org/wiki/Special:FilePath/' + f + '?width=900';
const PINPOINT_PLACES = [
  { en:'Eiffel Tower', ar:'برج إيفل', lat:48.858, lon:2.294, img:WM('Tour_Eiffel_Wikimedia_Commons.jpg') },
  { en:'Petra', ar:'البتراء', lat:30.329, lon:35.444, img:WM('Al_Khazneh_Petra_edit_2.jpg') },
  { en:'Machu Picchu', ar:'ماتشو بيتشو', lat:-13.163, lon:-72.545, img:WM('Machu_Picchu,_Peru.jpg') },
  { en:'Pyramids of Giza', ar:'أهرامات الجيزة', lat:29.979, lon:31.134, img:WM('Kheops-Pyramid.jpg') },
  { en:'Taj Mahal', ar:'تاج محل', lat:27.175, lon:78.042, img:WM('Taj_Mahal_(Edited).jpeg') },
  { en:'Statue of Liberty', ar:'تمثال الحرية', lat:40.689, lon:-74.045, img:WM('Statue_of_Liberty_7.jpg') },
  { en:'Colosseum', ar:'الكولوسيوم', lat:41.890, lon:12.492, img:WM('Colosseo_2020.jpg') },
  { en:'Burj Khalifa', ar:'برج خليفة', lat:25.197, lon:55.274, img:WM('Burj_Khalifa.jpg') },
  { en:'Great Wall of China', ar:'سور الصين العظيم', lat:40.432, lon:116.570, img:WM('The_Great_Wall_of_China_at_Jinshanling-edit.jpg') },
  { en:'Sydney Opera House', ar:'دار أوبرا سيدني', lat:-33.857, lon:151.215, img:WM('Sydney_Opera_House_-_Dec_2008.jpg') },
  { en:'Christ the Redeemer', ar:'تمثال المسيح الفادي', lat:-22.952, lon:-43.210, img:WM('Christ_the_Redeemer_-_Cristo_Redentor.jpg') },
  { en:'Golden Gate Bridge', ar:'جسر البوابة الذهبية', lat:37.820, lon:-122.478, img:WM('GoldenGateBridge-001.jpg') },
];

/* ===== MOST LIKELY TO ===== */
PACKS.mostlikely = {
  en: [
    { q: 'Who is most likely to become famous?' },
    { q: 'Who is most likely to survive a zombie apocalypse?' },
    { q: 'Who is most likely to cry at a movie?' },
    { q: 'Who is most likely to forget your birthday?' },
    { q: 'Who is most likely to become a millionaire?' },
    { q: 'Who is most likely to move abroad?' },
    { q: 'Who is most likely to eat the last piece of food without asking?' },
    { q: 'Who is most likely to still be awake at 4am?' },
    { q: 'Who is most likely to accidentally like an old photo?' },
    { q: 'Who is most likely to get lost using GPS?' },
    { q: 'Who is most likely to start a business?' },
    { q: 'Who is most likely to cancel plans at the last minute?' },
    { q: 'Who is most likely to talk to strangers in an elevator?' },
    { q: 'Who is most likely to become the most successful?' },
  ],
  ar: [
    { q: 'من الأرجح يصير مشهور؟' },
    { q: 'من الأرجح ينجو من غزو الزومبي؟' },
    { q: 'من الأرجح يبكي في فيلم؟' },
    { q: 'من الأرجح ينسى عيد ميلادك؟' },
    { q: 'من الأرجح يصير مليونير؟' },
    { q: 'من الأرجح يسافر ويعيش في الخارج؟' },
    { q: 'من الأرجح ياكل آخر قطعة أكل بدون ما يسأل؟' },
    { q: 'من الأرجح يكون صاحي الساعة 4 الصبح؟' },
    { q: 'من الأرجح يلايك صورة قديمة بالغلط؟' },
    { q: 'من الأرجح يضيع وهو يستخدم الخرايط؟' },
    { q: 'من الأرجح يفتح مشروع تجاري؟' },
    { q: 'من الأرجح يلغي الخطة اللحظة الأخيرة؟' },
    { q: 'من الأرجح يكلم ناس ما يعرفهم في المصعد؟' },
    { q: 'من الأرجح يكون الأنجح بينكم؟' },
  ],
};

/* ===== TRUE OR LIE ===== */
PACKS.trueorlie = {
  en: [
    { s: 'Cleopatra lived closer in time to the iPhone than to the pyramids being built', truth: true },
    { s: 'A group of flamingos is called a flamboyance', truth: true },
    { s: 'The Eiffel Tower grows taller in summer', truth: true },
    { s: 'Saudi Arabia imports sand from Australia', truth: true },
    { s: 'Octopuses have three hearts', truth: true },
    { s: "Scotland's national animal is the dragon", truth: false },
    { s: 'Oxford University is older than the Aztec Empire', truth: true },
    { s: 'A bolt of lightning is hotter than the surface of the Sun', truth: true },
    { s: 'Honey never expires', truth: true },
    { s: 'Finland has more saunas than cars', truth: true },
    { s: 'Napoleon was shorter than the average French man of his time', truth: false },
    { s: 'Bananas are berries but strawberries are not', truth: true },
  ],
  ar: [
    { s: 'كليوباترا عاشت أقرب زمنياً للآيفون من بناء الأهرامات', truth: true },
    { s: 'مجموعة طيور الفلامينغو تسمى فلامبويانس', truth: true },
    { s: 'برج إيفل يطول في الصيف', truth: true },
    { s: 'السعودية تستورد الرمل من أستراليا', truth: true },
    { s: 'الأخطبوط عنده ثلاثة قلوب', truth: true },
    { s: 'الحيوان الوطني لاسكتلندا هو التنين', truth: false },
    { s: 'جامعة أكسفورد أقدم من الحضارة الأزتيكية', truth: true },
    { s: 'الصاعقة أسخن من سطح الشمس', truth: true },
    { s: 'العسل لا يفسد', truth: true },
    { s: 'في فنلندا حمامات بخار أكثر من السيارات', truth: true },
    { s: 'نابليون كان أقصر من متوسط طول الفرنسي في زمنه', truth: false },
    { s: 'الموز نوع من التوت لكن الفراولة ليست كذلك', truth: true },
  ],
};

/* ===== FLAG HUNT ===== */
PACKS.flaghunt = {
  en: [
    { flag:'🇯🇵', options:['Japan','China','South Korea','Vietnam'], correct:0 },
    { flag:'🇧🇷', options:['Argentina','Colombia','Brazil','Mexico'], correct:2 },
    { flag:'🇩🇪', options:['Austria','Switzerland','Germany','Netherlands'], correct:2 },
    { flag:'🇸🇦', options:['UAE','Saudi Arabia','Kuwait','Bahrain'], correct:1 },
    { flag:'🇫🇷', options:['Belgium','France','Italy','Spain'], correct:1 },
    { flag:'🇦🇺', options:['New Zealand','Canada','Australia','South Africa'], correct:2 },
    { flag:'🇪🇬', options:['Syria','Jordan','Libya','Egypt'], correct:3 },
    { flag:'🇹🇷', options:['Greece','Turkey','Iran','Iraq'], correct:1 },
    { flag:'🇰🇷', options:['North Korea','Japan','South Korea','China'], correct:2 },
    { flag:'🇮🇳', options:['Pakistan','Bangladesh','India','Sri Lanka'], correct:2 },
    { flag:'🇴🇲', options:['UAE','Oman','Qatar','Bahrain'], correct:1 },
    { flag:'🇰🇼', options:['Kuwait','Bahrain','Qatar','Jordan'], correct:0 },
    { flag:'🇲🇦', options:['Algeria','Tunisia','Morocco','Libya'], correct:2 },
  ],
  ar: [
    { flag:'🇯🇵', options:['اليابان','الصين','كوريا الجنوبية','فيتنام'], correct:0 },
    { flag:'🇧🇷', options:['الأرجنتين','كولومبيا','البرازيل','المكسيك'], correct:2 },
    { flag:'🇩🇪', options:['النمسا','سويسرا','ألمانيا','هولندا'], correct:2 },
    { flag:'🇸🇦', options:['الإمارات','السعودية','الكويت','البحرين'], correct:1 },
    { flag:'🇫🇷', options:['بلجيكا','فرنسا','إيطاليا','إسبانيا'], correct:1 },
    { flag:'🇦🇺', options:['نيوزيلندا','كندا','أستراليا','جنوب أفريقيا'], correct:2 },
    { flag:'🇪🇬', options:['سوريا','الأردن','ليبيا','مصر'], correct:3 },
    { flag:'🇹🇷', options:['اليونان','تركيا','إيران','العراق'], correct:1 },
    { flag:'🇴🇲', options:['الإمارات','عُمان','قطر','البحرين'], correct:1 },
    { flag:'🇰🇼', options:['الكويت','البحرين','قطر','الأردن'], correct:0 },
    { flag:'🇲🇦', options:['الجزائر','تونس','المغرب','ليبيا'], correct:2 },
    { flag:'🇰🇷', options:['كوريا الشمالية','اليابان','كوريا الجنوبية','الصين'], correct:2 },
    { flag:'🇮🇳', options:['باكستان','بنغلاديش','الهند','سريلانكا'], correct:2 },
  ],
};

/* ===== HIGHER OR LOWER ===== */
PACKS.higherlow = {
  en: [
    { q: 'How many bones in the adult human body?', n: 206, unit: 'bones' },
    { q: 'How many hours a day does a koala sleep?', n: 22, unit: 'hours' },
    { q: 'In what year was the first iPhone released?', n: 2007, unit: '' },
    { q: 'How many countries are in Africa?', n: 54, unit: 'countries' },
    { q: 'How many teeth does an adult human have?', n: 32, unit: 'teeth' },
    { q: 'How tall is the Burj Khalifa in meters?', n: 828, unit: 'meters' },
    { q: 'How many languages are spoken in the world?', n: 7000, unit: 'languages' },
    { q: 'How many episodes did Friends have?', n: 236, unit: 'episodes' },
    { q: 'How many muscles does the human body have?', n: 600, unit: 'muscles' },
    { q: 'How old is the Earth in billions of years?', n: 4, unit: 'billion years' },
  ],
  ar: [
    { q: 'كم عدد عظام جسم الإنسان البالغ؟', n: 206, unit: 'عظمة' },
    { q: 'كم ساعة ينام الكوالا في اليوم؟', n: 22, unit: 'ساعة' },
    { q: 'في أي سنة صدر أول آيفون؟', n: 2007, unit: '' },
    { q: 'كم دولة في أفريقيا؟', n: 54, unit: 'دولة' },
    { q: 'كم سناً يملك الإنسان البالغ؟', n: 32, unit: 'سناً' },
    { q: 'كم ارتفاع برج خليفة بالأمتار؟', n: 828, unit: 'متر' },
    { q: 'كم لغة تتحدث في العالم؟', n: 7000, unit: 'لغة' },
    { q: 'كم حلقة كان في مسلسل Friends؟', n: 236, unit: 'حلقة' },
    { q: 'كم عضلة في جسم الإنسان؟', n: 600, unit: 'عضلة' },
    { q: 'كم عمر الأرض بالمليار سنة؟', n: 4, unit: 'مليار سنة' },
  ],
};

/* ===== 2 TRUTHS 1 LIE ===== */
PACKS['2t1l'] = { en: [], ar: [] };

/* ===== EMOJI PHRASE ===== */
PACKS.emojiphrase = {
  en: [
    { e:'💰🗣️', options:['Put your money where your mouth is','Time is money','Actions speak louder','Money talks'], correct:0 },
    { e:'🐦✋', options:['Bird in hand is worth two in the bush','Kill two birds','Early bird','Free as a bird'], correct:0 },
    { e:'🍰🎂🍕🍟', options:['Cheat day','You cannot have your cake and eat it','Comfort food','Fast food'], correct:1 },
    { e:'🌊🌊🌊', options:['Making waves','Rough seas','Third time charm','Go with the flow'], correct:0 },
    { e:'👁️🍵', options:['Eye of the storm','I spy','Seeing clearly','Eye for an eye'], correct:1 },
    { e:'🐎🏪', options:["Don't look a gift horse in the mouth","Wild West","Horse trading","Get back on horse"], correct:0 },
  ],
  ar: [
    { e:'💰🗣️', options:['حط فلوسك فين كلامك','الوقت من ذهب','الأفعال أبلغ','المال يتكلم'], correct:3 },
    { e:'🐦✋', options:['عصفور في اليد خير من عشرة على الشجرة','اقتل عصفورين بحجر','الطير الباكر','حر مثل الطير'], correct:0 },
    { e:'🍰🎂🍕🍟', options:['يوم غش','ما تقدر تاكل الكيكة وتحتفظ بها','أكل مريح','وجبات سريعة'], correct:1 },
    { e:'🌊🌊🌊', options:['تصنع أمواج','بحر هايج','ثالثة الأثافي','اجري مع التيار'], correct:0 },
    { e:'👁️🍵', options:['عين العاصفة','أنا أتجسس','شايف بوضوح','العين بالعين'], correct:1 },
    { e:'🐎🏪', options:['ما تحكم على هدية','الغرب الوحشي','تجارة الخيل','ارجع واركب'], correct:0 },
  ],
};

/* ===== EMOJI WORD ===== */
PACKS.emojiword = {
  en: [
    { e:'🌙🔦', options:['Flashlight','Moonlight','Starlight','Midnight'], correct:1 },
    { e:'🔥🚒', options:['Firefighter','Hot car','Emergency','Fire truck'], correct:0 },
    { e:'📚🐛', options:['Library','Bookworm','Study bug','Reading list'], correct:1 },
    { e:'🦁👑', options:['King of jungle','Lion king','Pride leader','Animal kingdom'], correct:1 },
    { e:'☀️🕶️', options:['Sunglasses','Beach vibes','Summer','Sunshine'], correct:0 },
    { e:'🐝📖', options:['Bug book','Spelling bee','Honeybee','Nature book'], correct:1 },
    { e:'🍎👩‍🏫', options:['Fruit teacher','Apple for teacher','School lunch','Biology'], correct:1 },
    { e:'🌹🔫', options:['Gunslinger','Shotgun','Florist','Guns and roses'], correct:3 },
  ],
  ar: [
    { e:'🌙🔦', options:['مصباح يدوي','ضوء القمر','ضوء النجوم','منتصف الليل'], correct:1 },
    { e:'🔥🚒', options:['رجل إطفاء','سيارة حارة','طوارئ','سيارة إطفاء'], correct:0 },
    { e:'📚🐛', options:['مكتبة','دودة كتب','حشرة دراسة','قائمة قراءة'], correct:1 },
    { e:'🦁👑', options:['ملك الغابة','أسد الملك','قائد الفخر','مملكة الحيوان'], correct:1 },
    { e:'☀️🕶️', options:['نظارات شمسية','أجواء شاطئ','صيف','ضوء شمس'], correct:0 },
    { e:'🐝📖', options:['كتاب حشرات','مسابقة تهجئة','نحلة','كتاب طبيعة'], correct:1 },
    { e:'🍎👩‍🏫', options:['معلمة الفواكه','تفاحة للمعلمة','غداء المدرسة','أحياء'], correct:1 },
    { e:'🌹🔫', options:['مسلح','بندقية','بائع زهور','غانز آند روزز'], correct:3 },
  ],
};

/* ===== EMOJI PLACE ===== */
PACKS.emojiplace = {
  en: [
    { answer:'PARIS', category:'City', e:'🐾🌹', parts:['paw','ris'], explanation:'Paw + ris = Paris' },
    { answer:'TOKYO', category:'City', e:'👣🏆🎏', parts:['toe','key','o'], explanation:'Toe + key + o = Tokyo' },
    { answer:'DUBAI', category:'City', e:'2️⃣🐝', parts:['do','bye'], explanation:'Doo + bye = Dubai' },
    { answer:'LONDON', category:'City', e:'🦁🔔', parts:['lon','don'], explanation:'Lon + don = London' },
    { answer:'BERLIN', category:'City', e:'🐻🔗', parts:['bear','lin'], explanation:'Bear + lin = Berlin' },
    { answer:'MOSCOW', category:'City', e:'🐁🦅', parts:['mos','cow'], explanation:'Mos + cow = Moscow' },
    { answer:'JORDAN', category:'Country', e:'🃏🦬', parts:['jor','dan'], explanation:'Jor + dan = Jordan' },
    { answer:'CANADA', category:'Country', e:'🐱🐣🐦', parts:['can','a','da'], explanation:'Can + a + da = Canada' },
    { answer:'SWEDEN', category:'Country', e:'💦🦷', parts:['swee','den'], explanation:'Swee + den = Sweden' },
    { answer:'GREECE', category:'Country', e:'😄🦦', parts:['gree','ce'], explanation:'Gree + ce = Greece' },
    { answer:'NORWAY', category:'Country', e:'🚪🛣️', parts:['nor','way'], explanation:'Nor + way = Norway' },
    { answer:'BRAZIL', category:'Country', e:'🍺🦁', parts:['bra','zil'], explanation:'Bra + zil = Brazil' },
    { answer:'KUWAIT', category:'Country', e:'🐄8️⃣', parts:['ku','wait'], explanation:'Ku + wait = Kuwait' },
    { answer:'BAHRAIN', category:'Country', e:'🍺🌧️', parts:['bah','rain'], explanation:'Bah + rain = Bahrain' },
    { answer:'TAIWAN', category:'Country', e:'👔1️⃣', parts:['tie','one'], explanation:'Tie + one = Taiwan' },
    { answer:'IRELAND', category:'Country', e:'👁️🌍', parts:['ire','land'], explanation:'Ire + land = Ireland' },
  ],
  ar: [
    { answer:'باريس', category:'مدينة', e:'🐾🌹', parts:['paw','ris'], explanation:'Paw + ris = Paris' },
    { answer:'طوكيو', category:'مدينة', e:'👣🏆🎏', parts:['toe','key','o'], explanation:'Toe + key + o = Tokyo' },
    { answer:'دبي', category:'مدينة', e:'2️⃣🐝', parts:['do','bye'], explanation:'Doo + bye = Dubai' },
    { answer:'لندن', category:'مدينة', e:'🦁🔔', parts:['lon','don'], explanation:'Lon + don = London' },
    { answer:'برلين', category:'مدينة', e:'🐻🔗', parts:['bear','lin'], explanation:'Bear + lin = Berlin' },
    { answer:'موسكو', category:'مدينة', e:'🐁🦅', parts:['mos','cow'], explanation:'Mos + cow = Moscow' },
    { answer:'الأردن', category:'دولة', e:'🃏🦬', parts:['jor','dan'], explanation:'Jor + dan = Jordan' },
    { answer:'كندا', category:'دولة', e:'🐱🐣🐦', parts:['can','a','da'], explanation:'Can + a + da = Canada' },
    { answer:'الكويت', category:'دولة', e:'🐄8️⃣', parts:['ku','wait'], explanation:'Ku + wait = Kuwait' },
    { answer:'البحرين', category:'دولة', e:'🍺🌧️', parts:['bah','rain'], explanation:'Bah + rain = Bahrain' },
  ],
};

/* ===== BLUFF (LIE DETECTOR) static fallback ===== */
PACKS.bluff = {
  en: [
    { fact:'The average person walks ___ miles in a lifetime', truth:'100,000', lies:['50,000','200,000'] },
    { fact:'Honey never expires. Archaeologists found ___ year old honey in Egypt', truth:'3,000', lies:['500','10,000'] },
    { fact:'A day on Venus is longer than a ___ on Venus', truth:'year', lies:['month','decade'] },
    { fact:'Cleopatra lived closer to the ___ than to the pyramids being built', truth:'Moon landing', lies:['birth of Jesus','invention of writing'] },
    { fact:'The shortest war in history lasted ___ minutes', truth:'38', lies:['90','180'] },
    { fact:'Octopuses have ___ hearts', truth:'three', lies:['two','five'] },
    { fact:'The Eiffel Tower can be ___ cm taller in summer', truth:'15', lies:['2','50'] },
    { fact:'Oxford University is older than the ___ Empire', truth:'Aztec', lies:['Roman','Ottoman'] },
    { fact:'Bananas are technically a ___', truth:'berry', lies:['vegetable','root'] },
    { fact:'A bolt of lightning is five times hotter than the ___', truth:'surface of the Sun', lies:['core of the Earth','inside of a volcano'] },
    { fact:'Wombats produce ___ shaped poo', truth:'cube', lies:['spiral','pyramid'] },
    { fact:'Scotland\'s national animal is the ___', truth:'unicorn', lies:['lion','thistle'] },
    { fact:'The inventor of the Pringles can is buried ___', truth:'in a Pringles can', lies:['with a patent','in Ohio'] },
    { fact:'Saudi Arabia imports ___ from Australia', truth:'sand', lies:['camels','dates'] },
    { fact:'Finland has more ___ than cars', truth:'saunas', lies:['lakes','bicycles'] },
  ],
  ar: [
    { fact:'المتوسط يمشي ___ ميل في حياته', truth:'١٠٠٫٠٠٠', lies:['٥٠٫٠٠٠','٢٠٠٫٠٠٠'] },
    { fact:'العسل لا يفسد — لقوا عسل عمره ___ سنة في مصر', truth:'٣٠٠٠', lies:['٥٠٠','١٠٫٠٠٠'] },
    { fact:'الأخطبوط عنده ___ قلوب', truth:'ثلاثة', lies:['اثنين','خمسة'] },
    { fact:'برج إيفل يطول ___ سم في الصيف', truth:'١٥', lies:['٢','٥٠'] },
    { fact:'جامعة أكسفورد أقدم من الحضارة ___', truth:'الأزتيكية', lies:['الرومانية','العثمانية'] },
    { fact:'الموز من الناحية العلمية هو ___', truth:'توت', lies:['خضار','فاكهة جافة'] },
    { fact:'الصاعقة أسخن بخمس مرات من ___', truth:'سطح الشمس', lies:['مركز الأرض','الحمم البركانية'] },
    { fact:'الحيوان الوطني لاسكتلندا هو ___', truth:'وحيد القرن', lies:['الأسد','النمر'] },
    { fact:'السعودية تستورد ___ من أستراليا', truth:'رمال', lies:['إبل','تمر'] },
    { fact:'في فنلندا ___ أكثر من السيارات', truth:'حمامات بخار', lies:['بحيرات','دراجات'] },
    { fact:'أقصر حرب في التاريخ استمرت ___ دقيقة', truth:'٣٨', lies:['٩٠','١٨٠'] },
    { fact:'كليوباترا عاشت أقرب لـ ___ من بناء الأهرامات', truth:'رحلة القمر', lies:['ميلاد المسيح','اختراع الكتابة'] },
    { fact:'مخترع علبة برينغلز مدفون ___', truth:'في علبة برينغلز', lies:['بجانب براءة اختراعه','في أوهايو'] },
    { fact:'الوومبات ينتج برازاً بشكل ___', truth:'مكعب', lies:['حلزوني','هرمي'] },
    { fact:'برج إيفل أُنشئ في الأصل كـ ___', truth:'هوائي راديو', lies:['برج مراقبة','متحف'] },
  ],
};

/* ===== WOULD YOU RATHER static fallback ===== */
PACKS.wyr = {
  en: [
    { q:'Would you rather never be able to use your phone again OR never watch TV or movies again?', a:'No phone', b:'No TV/movies' },
    { q:'Would you rather know when you will die OR how you will die?', a:'Know when', b:'Know how' },
    { q:'Would you rather be famous but hated OR unknown but loved?', a:'Famous but hated', b:'Unknown but loved' },
    { q:'Would you rather have the ability to fly OR be invisible?', a:'Fly', b:'Invisible' },
    { q:'Would you rather eat only spicy food forever OR never eat anything spicy again?', a:'Only spicy', b:'Never spicy' },
    { q:'Would you rather always have to tell the truth OR always lie?', a:'Always truth', b:'Always lie' },
    { q:'Would you rather be able to speak every language OR play every instrument?', a:'All languages', b:'All instruments' },
    { q:'Would you rather live in a world without music OR without internet?', a:'No music', b:'No internet' },
    { q:'Would you rather lose all your memories OR never make new ones?', a:'Lose all memories', b:'Never make new ones' },
    { q:'Would you rather be 10 years older OR 5 years younger right now?', a:'10 years older', b:'5 years younger' },
    { q:'Would you rather only be able to whisper OR only be able to shout?', a:'Only whisper', b:'Only shout' },
    { q:'Would you rather have free food for life OR free travel for life?', a:'Free food', b:'Free travel' },
    { q:'Would you rather know all the answers to every exam OR never have to sleep?', a:'All exam answers', b:'Never sleep' },
    { q:'Would you rather be able to read minds OR see the future?', a:'Read minds', b:'See future' },
    { q:'Would you rather fight 100 duck-sized horses OR one horse-sized duck?', a:'100 tiny horses', b:'One giant duck' },
  ],
  ar: [
    { q:'يا هذا يا هذا: ما تستخدم الجوال أبداً — ولا ما تشوف أفلام وتلفزيون أبداً؟', a:'بدون جوال', b:'بدون أفلام' },
    { q:'يا هذا يا هذا: تعرف متى تموت — ولا كيف تموت؟', a:'متى', b:'كيف' },
    { q:'يا هذا يا هذا: تكون مشهور لكن مكروه — ولا مجهول لكن محبوب؟', a:'مشهور ومكروه', b:'مجهول ومحبوب' },
    { q:'يا هذا يا هذا: تطير — ولا تصير غير مرئي؟', a:'أطير', b:'غير مرئي' },
    { q:'يا هذا يا هذا: أكل حار للأبد — ولا ما تاكل حار أبداً؟', a:'حار للأبد', b:'بدون حار أبداً' },
    { q:'يا هذا يا هذا: دائماً تقول الحقيقة — ولا دائماً تكذب؟', a:'دايم صادق', b:'دايم كاذب' },
    { q:'يا هذا يا هذا: تتكلم كل اللغات — ولا تعزف كل الآلات؟', a:'كل اللغات', b:'كل الآلات' },
    { q:'يا هذا يا هذا: عالم بدون موسيقى — ولا بدون إنترنت؟', a:'بدون موسيقى', b:'بدون إنترنت' },
    { q:'يا هذا يا هذا: تفقد كل ذكرياتك — ولا ما تقدر تسوي ذكريات جديدة أبداً؟', a:'أفقد الذكريات', b:'بدون ذكريات جديدة' },
    { q:'يا هذا يا هذا: أكبر بـ١٠ سنين — ولا أصغر بـ٥ سنين؟', a:'أكبر بـ١٠', b:'أصغر بـ٥' },
    { q:'يا هذا يا هذا: دايم تهمس — ولا دايم تصرخ؟', a:'دايم أهمس', b:'دايم أصرخ' },
    { q:'يا هذا يا هذا: أكل مجاني للأبد — ولا سفر مجاني للأبد؟', a:'أكل مجاني', b:'سفر مجاني' },
    { q:'يا هذا يا هذا: تقرأ الأفكار — ولا تشوف المستقبل؟', a:'أقرأ الأفكار', b:'أشوف المستقبل' },
    { q:'يا هذا يا هذا: تحارب ١٠٠ فرسة بحجم بطة — ولا بطة واحدة بحجم فرس؟', a:'١٠٠ فرسة صغيرة', b:'بطة ضخمة واحدة' },
    { q:'يا هذا يا هذا: تعرف كل إجابات كل الامتحانات — ولا ما تحتاج نوم أبداً؟', a:'كل الإجابات', b:'بدون نوم' },
  ],
};

/* ===== CONFESSIONS (INTERROGATION) static fallback ===== */
PACKS.interrogation = {
  en: [
    { q:'What is the most embarrassing thing you\'ve ever done in public?' },
    { q:'What is something you pretend to like but actually hate?' },
    { q:'What is the most childish thing you still do?' },
    { q:'What is a weird food combination you secretly enjoy?' },
    { q:'What is the longest you have gone without showering?' },
    { q:'What is something you have lied to your parents about?' },
    { q:'What app on your phone would be most embarrassing if everyone could see your history?' },
    { q:'What is something you are weirdly competitive about?' },
    { q:'What is a song you are embarrassed to admit you love?' },
    { q:'What is the most ridiculous thing you have ever cried about?' },
    { q:'What is something you have secretly Googled that you would never admit?' },
    { q:'What is the pettiest reason you have ever ended a friendship?' },
    { q:'What is the most illegal thing you have ever done?' },
    { q:'What is something you have faked to get out of plans?' },
    { q:'What is the dumbest thing you have spent money on?' },
  ],
  ar: [
    { q:'إيش أكثر شيء محرج سويته في العلن؟' },
    { q:'إيش شيء تتظاهر تحبه بس في الحقيقة تكرهه؟' },
    { q:'إيش أكثر شيء طفولي لا تزال تسويه؟' },
    { q:'إيش مزيج أكل غريب تحبه سراً؟' },
    { q:'أطول فترة ما استحميت فيها؟' },
    { q:'إيش شيء كذبت فيه على أهلك؟' },
    { q:'إيش تطبيق في جوالك يحرجك لو شاف الكل سجل استخدامك؟' },
    { q:'إيش شيء تنافسي فيه بشكل غريب؟' },
    { q:'إيش أغنية تستحي تعترف أنك تحبها؟' },
    { q:'إيش أسخف شيء بكيت عليه؟' },
    { q:'إيش سؤال بحثت عنه في جوجل ما تقدر تعترف فيه؟' },
    { q:'أتفه سبب قاطعت فيه صاحب؟' },
    { q:'أكثر شيء غير قانوني سويته في حياتك؟' },
    { q:'إيش عذر اخترعته عشان تهرب من خطة مع ناس؟' },
    { q:'أغبى شيء صرفت عليه فلوس؟' },
  ],
};

/* ===== ROAST BATTLE (DISS) static fallback ===== */
PACKS.diss = {
  en: [
    { prompt:'Your opponent looks like they googled "business casual" and still got it wrong. Roast their fashion sense.' },
    { prompt:'Your opponent peaked in high school and everyone knows it. Roast them.' },
    { prompt:'Your opponent takes 47 photos to post one on Instagram. Roast their need for validation.' },
    { prompt:'Your opponent texts back three days later with "lol". Roast their communication skills.' },
    { prompt:'Your opponent has a "I\'m not like other people" personality. Roast them.' },
    { prompt:'Your opponent still uses their ex\'s Netflix. Roast their life choices.' },
    { prompt:'Your opponent gives unsolicited life advice but has no life together. Roast them.' },
    { prompt:'Your opponent calls themselves an entrepreneur but just sells things online. Roast them.' },
    { prompt:'Your opponent says "I\'m literally dying" about everything minor. Roast their dramatics.' },
    { prompt:'Your opponent skips leg day every single week. Roast their commitment issues.' },
    { prompt:'Your opponent orders the most complicated drink at a coffee shop. Roast their personality.' },
    { prompt:'Your opponent still lives with their parents at this age. Roast their independence.' },
    { prompt:'Your opponent has 11 unread notifications and a 47% battery. Roast their life management.' },
    { prompt:'Your opponent has never finished a single TV show. Roast their commitment.' },
    { prompt:'Your opponent thinks they are funny but the room goes quiet when they joke. Roast them.' },
  ],
  ar: [
    { prompt:'خصمك يبدو إنه بحث عن "لبس رسمي" وما فاهم النتيجة. اهجوا ذوقه بالملابس.' },
    { prompt:'خصمك بلغ ذروته في المدرسة الثانوية والكل يعرف. اهجوه.' },
    { prompt:'خصمك يسوي ٤٧ صورة عشان ينشر واحدة. اهجو احتياجه للإعجاب.' },
    { prompt:'خصمك يرد على الرسائل بعد ثلاثة أيام بـ"هههه". اهجو تواصله.' },
    { prompt:'خصمك عنده شخصية "أنا مختلف عن الناس". اهجوه.' },
    { prompt:'خصمك لا يزال يستخدم نتفليكس طليقه السابق. اهجو قراراته في الحياة.' },
    { prompt:'خصمك يعطي نصائح الحياة بس حياته فوضى. اهجوه.' },
    { prompt:'خصمك يسمي نفسه رجل أعمال بس بيبيع أشياء أونلاين. اهجوه.' },
    { prompt:'خصمك يقول "أنا ميت" على كل شيء بسيط. اهجو دراما حياته.' },
    { prompt:'خصمك يتخطى تمرين الأرجل كل أسبوع. اهجو التزامه.' },
    { prompt:'خصمك يطلب أصعب مشروب في المقهى. اهجو شخصيته.' },
    { prompt:'خصمك لم ينهِ أي مسلسل في حياته. اهجو التزامه.' },
    { prompt:'خصمك يحسب نفسه مضحك بس الغرفة تصمت لما يمزح. اهجوه.' },
    { prompt:'خصمك عنده ١١ إشعار غير مقروء وبطارية ٤٧٪. اهجو تنظيمه لحياته.' },
    { prompt:'خصمك يعيش مع أهله في هذا العمر. اهجو استقلاليته.' },
  ],
};

/* ===== QUIZ (QUESTIONS) static fallback ===== */
PACKS.quiz = {
  en: [
    { q:'What is the capital of Australia?', options:['Sydney','Melbourne','Canberra','Brisbane'], correct:2, cat:'geography' },
    { q:'How many sides does a hexagon have?', options:['5','6','7','8'], correct:1, cat:'math' },
    { q:'Which planet is closest to the Sun?', options:['Venus','Earth','Mercury','Mars'], correct:2, cat:'science' },
    { q:'What language is spoken in Brazil?', options:['Spanish','Portuguese','French','English'], correct:1, cat:'geography' },
    { q:'Who painted the Mona Lisa?', options:['Michelangelo','Van Gogh','Leonardo da Vinci','Picasso'], correct:2, cat:'art' },
    { q:'What is the fastest land animal?', options:['Lion','Cheetah','Horse','Leopard'], correct:1, cat:'animals' },
    { q:'How many bones does an adult human have?', options:['206','186','226','196'], correct:0, cat:'science' },
    { q:'What is the chemical symbol for gold?', options:['Go','Gd','Au','Ag'], correct:2, cat:'science' },
    { q:'Which country invented pizza?', options:['Greece','USA','France','Italy'], correct:3, cat:'food' },
    { q:'What year did World War II end?', options:['1943','1944','1945','1946'], correct:2, cat:'history' },
    { q:'What is the largest ocean?', options:['Atlantic','Indian','Arctic','Pacific'], correct:3, cat:'geography' },
    { q:'How many teeth does an adult human have?', options:['28','30','32','34'], correct:2, cat:'science' },
    { q:'Who wrote Romeo and Juliet?', options:['Charles Dickens','William Shakespeare','Jane Austen','Mark Twain'], correct:1, cat:'literature' },
    { q:'What is the capital of Japan?', options:['Osaka','Kyoto','Tokyo','Hiroshima'], correct:2, cat:'geography' },
    { q:'Which gas do plants absorb from the air?', options:['Oxygen','Nitrogen','Carbon Dioxide','Hydrogen'], correct:2, cat:'science' },
    { q:'What is the longest river in the world?', options:['Amazon','Congo','Yangtze','Nile'], correct:3, cat:'geography' },
    { q:'How many players are on a basketball team on court?', options:['4','5','6','7'], correct:1, cat:'sport' },
    { q:'What year was the first iPhone released?', options:['2005','2006','2007','2008'], correct:2, cat:'technology' },
    { q:'Which country has the most World Cup wins?', options:['Germany','Argentina','Italy','Brazil'], correct:3, cat:'sport' },
    { q:'What is the square root of 144?', options:['11','12','13','14'], correct:1, cat:'math' },
  ],
  ar: [
    { q:'ما عاصمة أستراليا؟', options:['سيدني','ملبورن','كانبيرا','بريزبن'], correct:2, cat:'geography' },
    { q:'كم ضلع للسداسي؟', options:['٥','٦','٧','٨'], correct:1, cat:'math' },
    { q:'أي كوكب هو الأقرب للشمس؟', options:['الزهرة','الأرض','عطارد','المريخ'], correct:2, cat:'science' },
    { q:'ما اللغة الرسمية في البرازيل؟', options:['إسبانية','برتغالية','فرنسية','إنجليزية'], correct:1, cat:'geography' },
    { q:'من رسم الموناليزا؟', options:['مايكل أنجلو','فان جوخ','ليوناردو دافينشي','بيكاسو'], correct:2, cat:'art' },
    { q:'ما أسرع حيوان بري؟', options:['أسد','فهد','حصان','نمر'], correct:1, cat:'animals' },
    { q:'كم عدد عظام الإنسان البالغ؟', options:['٢٠٦','١٨٦','٢٢٦','١٩٦'], correct:0, cat:'science' },
    { q:'ما الرمز الكيميائي للذهب؟', options:['Go','Gd','Au','Ag'], correct:2, cat:'science' },
    { q:'أي بلد اخترعت البيتزا؟', options:['اليونان','أمريكا','فرنسا','إيطاليا'], correct:3, cat:'food' },
    { q:'متى انتهت الحرب العالمية الثانية؟', options:['١٩٤٣','١٩٤٤','١٩٤٥','١٩٤٦'], correct:2, cat:'history' },
    { q:'ما أكبر محيط؟', options:['الأطلسي','الهندي','المتجمد الشمالي','الهادئ'], correct:3, cat:'geography' },
    { q:'كم سن للإنسان البالغ؟', options:['٢٨','٣٠','٣٢','٣٤'], correct:2, cat:'science' },
    { q:'من كتب روميو وجولييت؟', options:['تشارلز ديكنز','شكسبير','جين أوستن','مارك توين'], correct:1, cat:'literature' },
    { q:'ما عاصمة اليابان؟', options:['أوساكا','كيوتو','طوكيو','هيروشيما'], correct:2, cat:'geography' },
    { q:'ما الغاز الذي تمتصه النباتات من الهواء؟', options:['أكسجين','نيتروجين','ثاني أكسيد الكربون','هيدروجين'], correct:2, cat:'science' },
    { q:'ما أطول نهر في العالم؟', options:['الأمازون','الكونغو','يانغتسي','النيل'], correct:3, cat:'geography' },
    { q:'كم عدد لاعبي كرة السلة في الملعب؟', options:['٤','٥','٦','٧'], correct:1, cat:'sport' },
    { q:'متى صدر أول آيفون؟', options:['٢٠٠٥','٢٠٠٦','٢٠٠٧','٢٠٠٨'], correct:2, cat:'technology' },
    { q:'أي دولة فازت بأكبر عدد من كؤوس العالم؟', options:['ألمانيا','الأرجنتين','إيطاليا','البرازيل'], correct:3, cat:'sport' },
    { q:'ما الجذر التربيعي لـ ١٤٤؟', options:['١١','١٢','١٣','١٤'], correct:1, cat:'math' },
  ],
};

/* ===== TIME MACHINE (YEAR) static fallback ===== */
PACKS.year = {
  en: [
    { q:'The first iPhone was released', y:2007 },
    { q:'Man first walked on the Moon', y:1969 },
    { q:'The Titanic sank', y:1912 },
    { q:'Burj Khalifa officially opened', y:2010 },
    { q:'The FIFA World Cup was held in Qatar', y:2022 },
    { q:'Facebook was founded', y:2004 },
    { q:'The Berlin Wall fell', y:1989 },
    { q:'The first Harry Potter book was published', y:1997 },
    { q:'YouTube was launched', y:2005 },
    { q:'Sultan Qaboos began his reign in Oman', y:1970 },
    { q:'The UAE was founded', y:1971 },
    { q:'WhatsApp was launched', y:2009 },
    { q:'The first FIFA World Cup was played', y:1930 },
    { q:'Google was founded', y:1998 },
    { q:'Netflix started streaming online', y:2007 },
    { q:'Instagram was launched', y:2010 },
    { q:'TikTok was launched globally', y:2018 },
    { q:'COVID-19 pandemic began', y:2020 },
    { q:'The Eiffel Tower was built', y:1889 },
    { q:'Amazon was founded', y:1994 },
  ],
  ar: [
    { q:'صدر أول آيفون', y:2007 },
    { q:'أول هبوط للإنسان على القمر', y:1969 },
    { q:'غرقت سفينة التايتنك', y:1912 },
    { q:'افتتح برج خليفة رسمياً', y:2010 },
    { q:'أقيم كأس العالم في قطر', y:2022 },
    { q:'تأسس فيسبوك', y:2004 },
    { q:'سقط جدار برلين', y:1989 },
    { q:'صدر أول كتاب هاري بوتر', y:1997 },
    { q:'انطلق يوتيوب', y:2005 },
    { q:'تولى السلطان قابوس الحكم في عمان', y:1970 },
    { q:'تأسست دولة الإمارات', y:1971 },
    { q:'انطلق واتساب', y:2009 },
    { q:'أقيم أول كأس عالم لكرة القدم', y:1930 },
    { q:'تأسست جوجل', y:1998 },
    { q:'بدأ نتفليكس بث الأفلام', y:2007 },
    { q:'انطلق انستغرام', y:2010 },
    { q:'انتشر تيك توك عالمياً', y:2018 },
    { q:'بدأ وباء كوفيد-١٩', y:2020 },
    { q:'بُني برج إيفل', y:1889 },
    { q:'تأسست أمازون', y:1994 },
  ],
};
