/* HYPOX — content packs (original, bilingual) + AI hook
   AI HOOK: set window.HYPOX_CONFIG.aiEndpoint to a URL on your Railway backend.
   POST { mode, lang, count } -> { prompts: [...] } matching the shapes below.
   If unset or the request fails, local packs are used. */

const PACKS = {
  /* ---- BLUFF BANQUET: { fact: text with ___ , truth } ---- */
  bluff: {
    en: [
      { fact: 'In Switzerland, it is illegal to own ___', truth: 'JUST ONE GUINEA PIG (they get lonely)' },
      { fact: 'The Dubai Police supercar fleet famously includes ___', truth: 'A BUGATTI VEYRON' },
      { fact: 'Australia regularly exports ___ to Saudi Arabia', truth: 'CAMELS' },
      { fact: 'Astronauts in space temporarily become ___', truth: 'ABOUT 5CM TALLER' },
      { fact: 'Archaeologists found 3,000-year-old ___ in Egyptian tombs — still edible', truth: 'HONEY' },
      { fact: 'To make it rain more, the UAE uses ___', truth: 'CLOUD-SEEDING DRONES' },
      { fact: 'An octopus has three ___', truth: 'HEARTS' },
      { fact: 'The Eiffel Tower gets about 15cm ___ every summer', truth: 'TALLER (metal expands)' },
      { fact: 'Botanically speaking, a banana is actually ___', truth: 'A BERRY' },
      { fact: 'In Japan, a train station stayed open for years to serve ___', truth: 'ONE SINGLE STUDENT' },
      { fact: 'Scotland’s official national animal is ___', truth: 'THE UNICORN' },
      { fact: 'A single strand of spaghetti is called ___', truth: 'A SPAGHETTO' },
      { fact: 'Cleopatra lived closer in time to ___ than to the pyramids being built', truth: 'THE IPHONE' },
      { fact: 'Oxford University is older than the ___ Empire', truth: 'AZTEC' },
      { fact: 'A group of flamingos is called a ___', truth: 'FLAMBOYANCE' },
      { fact: 'The loudest animal on Earth is the ___', truth: 'SPERM WHALE' },
      { fact: 'Nintendo was originally founded in ___ as a playing card company', truth: '1889' },
      { fact: 'A group of flamingos is called a ___', truth: 'FLAMBOYANCE' },
      { fact: 'The inventor of the telephone, Alexander Graham Bell, refused to have one in his ___', truth: 'STUDY (he found it distracting)' },
      { fact: 'Cleopatra lived closer in time to ___ than to the building of the pyramids', truth: 'THE IPHONE' },
      { fact: 'Oxford University is older than ___', truth: 'THE AZTEC EMPIRE' },
      { fact: 'A day on ___ is longer than its year', truth: 'VENUS' },
      { fact: 'The inventor of Pringles was buried in a ___', truth: 'PRINGLES CAN (per his request)' },
      { fact: 'Humans share about 60% of their DNA with ___', truth: 'BANANAS' },
      { fact: 'The Twitter bird has an official name: ___', truth: 'LARRY' },
      { fact: 'Nintendo was founded in ___', truth: '1889 (as a playing card company)' },
      { fact: 'In Japan, there is a ___ specifically for people who are too tired to talk', truth: 'SILENT TAXI SERVICE' },
      { fact: 'The average person walks about ___ in a lifetime', truth: '5 TIMES AROUND THE EARTH' },
      { fact: 'A bolt of lightning is five times hotter than the ___', truth: 'SURFACE OF THE SUN' },
    ],
    ar: [
      { fact: 'في سويسرا، يمنع قانونياً امتلاك ___', truth: 'خنزير غينيا واحد فقط (لأنه يحس بالوحدة)' },
      { fact: 'أسطول شرطة دبي للسيارات الفارهة يضم ___', truth: 'بوغاتي فيرون' },
      { fact: 'أستراليا تصدّر بانتظام ___ إلى السعودية', truth: 'الجِمال' },
      { fact: 'رواد الفضاء في الفضاء يصيرون مؤقتاً ___', truth: 'أطول بحوالي ٥ سم' },
      { fact: 'علماء الآثار لقوا ___ عمرها ٣٠٠٠ سنة في مقابر مصرية — ولا زالت صالحة للأكل', truth: 'عسل' },
      { fact: 'عشان تزيد الأمطار، الإمارات تستخدم ___', truth: 'طائرات مسيّرة لتلقيح السحب' },
      { fact: 'الأخطبوط عنده ثلاثة ___', truth: 'قلوب' },
      { fact: 'برج إيفل يزيد حوالي ١٥ سم ___ كل صيف', truth: 'طولاً (المعدن يتمدد)' },
      { fact: 'نباتياً، الموز يعتبر فعلياً ___', truth: 'نوع من التوت' },
      { fact: 'في اليابان، محطة قطار ظلت شغالة سنوات عشان تخدم ___', truth: 'طالبة وحدة فقط' },
      { fact: 'الحيوان الوطني الرسمي لاسكتلندا هو ___', truth: 'وحيد القرن الخرافي (يونيكورن)' },
      { fact: 'الخيط الواحد من السباغيتي اسمه ___', truth: 'سباغيتو' },
      { fact: 'كليوباترا عاشت أقرب زمنياً لـ ___ من بناء الأهرامات', truth: 'الآيفون' },
      { fact: 'جامعة أكسفورد أقدم من الإمبراطورية ___', truth: 'الأزتيكية' },
      { fact: 'مجموعة طيور الفلامينغو تُسمى ___', truth: 'Flamboyance' },
      { fact: 'أعلى حيوان صوتاً في العالم هو ___', truth: 'الحوت الأزرق' },
      { fact: 'نينتندو أُسست في ___ كشركة أوراق لعب', truth: '١٨٨٩' },
      { fact: 'مجموعة من الفلامينغو تُسمّى ___', truth: 'فلامبويانس (Flamboyance)' },
      { fact: 'مخترع التلفون رفض وجوده في ___', truth: 'مكتبه الخاص (كان يعتبره مشتتاً)' },
      { fact: 'كليوباترا عاشت أقرب زمنياً إلى ___ من بناء الأهرامات', truth: 'الآيفون' },
      { fact: 'جامعة أكسفورد أقدم من ___', truth: 'الحضارة الأزتيكية' },
      { fact: 'اليوم على كوكب ___ أطول من سنته', truth: 'الزهرة (فينوس)' },
      { fact: 'مخترع رقائق برينغلز دُفن داخل ___', truth: 'علبة برينغلز (بوصيته)' },
      { fact: 'البشر يشتركون مع ___ في ٦٠٪ من الحمض النووي', truth: 'الموز' },
      { fact: 'طائر تويتر له اسم رسمي هو ___', truth: 'لاري (Larry)' },
      { fact: 'نينتندو تأسست عام ___ كشركة أوراق لعب', truth: '١٨٨٩' },
      { fact: 'في اليابان، هناك ___ مخصص لمن هو متعب جداً للكلام', truth: 'خدمة تاكسي صامتة' },
      { fact: 'متوسط الإنسان يمشي في حياته مسافة ___', truth: '٥ مرات حول الأرض' },
      { fact: 'برق الصاعقة أسخن بـ٥ مرات من ___', truth: 'سطح الشمس' },
    ],
  },

  /* ---- WOULD YOU RATHER PERSONAL: { a, b } (target player answers) ---- */
  wyr: {
    en: [
      { a: 'Lose your phone for a month', b: 'Lose your car for a month' },
      { a: 'Only shawarma forever', b: 'Only machboos forever' },
      { a: 'Always 30 minutes late', b: 'Always 2 hours early' },
      { a: 'Know everyone’s salary', b: 'Everyone knows YOUR salary' },
      { a: 'A Gulf summer week with no AC', b: 'A Norway winter week with no jacket' },
      { a: 'Give up coffee forever', b: 'Give up karak forever' },
      { a: 'Famous on TikTok', b: 'Rich but completely anonymous' },
      { a: 'Only communicate in voice notes', b: 'Never send a voice note again' },
      { a: 'A wedding with 2,000 guests', b: 'Elope with only 10 people' },
      { a: 'Free flights forever (middle seat only)', b: 'One business-class trip per year' },
      { a: 'Live without music', b: 'Live without series & movies' },
      { a: 'Your search history goes public', b: 'Your bank statement goes public' },
      { a: 'Win 1 million but never travel again', b: 'Travel anywhere free forever but stay broke' },
      { a: 'Always know when someone is lying to you', b: 'Get away with any lie yourself' },
      { a: 'Have a personal chef', b: 'Have a personal driver' },
      { a: 'Live in your favorite city but hate your job', b: 'Dream job but live somewhere boring' },
      { a: 'Be the funniest person in any room', b: 'Be the smartest person in any room' },
      { a: 'Know what everyone thinks of you', b: 'Never know but always wonder' },
      { a: 'Eat the same meal every day for life', b: 'Never eat your favorite food again' },
      { a: 'Be always 10 minutes early', b: 'Always 10 minutes late' },
      { a: 'Have a rewind button for life (30 sec)', b: 'A pause button (freeze time)' },
      { a: 'Live in the city forever', b: 'Live in the countryside forever' },
      { a: 'Speak every language fluently', b: 'Play every instrument perfectly' },
      { a: 'No social media for a year', b: 'No music for a year' },
      { a: 'Be famous but broke', b: 'Rich but completely unknown' },
      { a: 'Always feel cold', b: 'Always feel too hot' },
      { a: 'Read minds but only hear bad thoughts', b: 'Never know what anyone thinks' },
      { a: 'Laugh uncontrollably at funerals', b: 'Cry uncontrollably at weddings' },
      { a: 'Be the funniest person in the room', b: 'Be the smartest person in the room' },
    ],
    ar: [
      { a: 'تفقد جوالك شهر كامل', b: 'تفقد سيارتك شهر كامل' },
      { a: 'شاورما بس لبقية عمرك', b: 'مچبوس بس لبقية عمرك' },
      { a: 'دايماً متأخر نص ساعة', b: 'دايماً مبكر ساعتين' },
      { a: 'تعرف رواتب الكل', b: 'الكل يعرف راتبك أنت' },
      { a: 'أسبوع صيف خليجي بدون مكيف', b: 'أسبوع شتاء نرويجي بدون جاكيت' },
      { a: 'تترك القهوة للأبد', b: 'تترك الكرك للأبد' },
      { a: 'مشهور بتيك توك', b: 'غني بس محد يعرفك' },
      { a: 'تتواصل بس بالرسائل الصوتية', b: 'ما ترسل رسالة صوتية أبداً' },
      { a: 'عرس بـ٢٠٠٠ معزوم', b: 'زواج بس بـ١٠ أشخاص' },
      { a: 'طيران مجاني للأبد (بس كرسي النص)', b: 'رحلة درجة أعمال وحدة بالسنة' },
      { a: 'تعيش بدون موسيقى', b: 'تعيش بدون مسلسلات وأفلام' },
      { a: 'سجل بحثك يصير عام', b: 'كشف حسابك البنكي يصير عام' },
      { a: 'تكسب مليون بس ما تسافر أبداً', b: 'تسافر مجاناً كل حياتك بس بدون فلوس' },
      { a: 'تعرف دايماً لو أحد يكذب عليك', b: 'تقدر تكذب على أي أحد وما يكتشف' },
      { a: 'عندك طباخ خاص', b: 'عندك سائق خاص' },
      { a: 'مدينتك المفضلة بوظيفة تكرهها', b: 'وظيفة أحلامك بمدينة مملة' },
      { a: 'أضحك شخص في أي غرفة', b: 'أذكى شخص في أي غرفة' },
      { a: 'تعرف ما يفكر فيه الكل عنك', b: 'ما تعرف أبداً وتتساءل دائماً' },
      { a: 'تاكل نفس الوجبة كل يوم للأبد', b: 'ما تاكل طعامك المفضل أبداً' },
      { a: 'دائماً مبكر ١٠ دقايق', b: 'دائماً متأخر ١٠ دقايق' },
      { a: 'زر رجوع في الحياة (٣٠ ثانية)', b: 'زر إيقاف مؤقت (تجمّد الوقت)' },
      { a: 'تسكن المدينة للأبد', b: 'تسكن الريف للأبد' },
      { a: 'تتكلم كل لغات العالم بطلاقة', b: 'تعزف كل الآلات الموسيقية باحتراف' },
      { a: 'بدون سوشيال ميديا لسنة كاملة', b: 'بدون موسيقى لسنة كاملة' },
      { a: 'مشهور لكن مفلس', b: 'غني لكن محد يعرفك' },
      { a: 'تحس ببرد دائماً', b: 'تحس بحر دائماً' },
      { a: 'تقرأ الأفكار لكن تسمع السلبي فقط', b: 'ما تعرف ما يفكر فيه أحد أبداً' },
      { a: 'تضحك بطريقة غير مسيطر عليها في الجنازات', b: 'تبكي بطريقة غير مسيطر عليها في الأعراس' },
      { a: 'أكثر شخص مضحك في الغرفة', b: 'أكثر شخص ذكي في الغرفة' },
    ],
  },

  /* ---- THE INTERROGATION: { q } (everyone answers anonymously) ---- */
  interrogation: {
    en: [
      { q: 'What’s the most childish thing you still do?' },
      { q: 'Your go-to excuse for leaving a gathering early?' },
      { q: 'You’re invisible for one day. First thing you do?' },
      { q: 'The weirdest thing you googled recently?' },
      { q: 'Your guilty-pleasure song or artist?' },
      { q: 'If you had to marry a food, which one?' },
      { q: 'A totally useless superpower you’d still take?' },
      { q: 'The most embarrassing thing in your screenshots folder?' },
      { q: 'A job you would be absolutely terrible at?' },
      { q: 'First thing you buy with 1 million?' },
      { q: 'A habit in this friend group that secretly annoys you?' },
      { q: 'The biggest lie you told your parents as a kid?' },
      { q: 'Something you pretend to like but secretly hate?' },
      { q: 'The last time you cried and why?' },
      { q: 'A red flag in yourself you keep ignoring?' },
      { q: 'The most money you wasted on something stupid?' },
      { q: 'Something you still do that you are too old for?' },
      { q: "What's something you pretend to like but actually hate?" },
      { q: "A secret talent you have that nobody knows about?" },
      { q: "The most embarrassing thing you've done in public?" },
      { q: "Something you do when you're completely alone that you'd never admit?" },
      { q: "Your honest opinion of the most annoying person in this room?" },
      { q: "The worst lie you've told and got away with?" },
      { q: "Something you're irrationally afraid of?" },
      { q: "A phase you went through that you regret?" },
      { q: "The most childish argument you've had recently?" },
      { q: "Your actual honest opinion of your own cooking?" },
      { q: "Something you've done that you'd be embarrassed if your parents knew?" },
      { q: "The pettiest thing you've ever done for revenge?" },
    ],
    ar: [
      { q: 'شنو أكثر تصرف طفولي للحين تسويه؟' },
      { q: 'شنو عذرك الجاهز للانسحاب من القعدة بدري؟' },
      { q: 'صرت خفي ليوم واحد. أول شي بتسويه؟' },
      { q: 'أغرب شي بحثت عنه في قوقل مؤخراً؟' },
      { q: 'أغنية أو فنان تستحي تعترف إنك تسمعه؟' },
      { q: 'لو لازم تتزوج أكلة، شنو تختار؟' },
      { q: 'قوة خارقة عديمة الفايدة بس تاخذها؟' },
      { q: 'أكثر شي محرج في ملف السكرين شوت عندك؟' },
      { q: 'وظيفة بتكون فيها فاشل تماماً؟' },
      { q: 'أول شي تشتريه بمليون؟' },
      { q: 'عادة في هالشلة تزعجك بسرّية؟' },
      { q: 'أكبر كذبة كذبتها على أهلك وأنت صغير؟' },
      { q: 'شي تتظاهر إنك تحبه بس في الحقيقة تكرهه؟' },
      { q: 'آخر مرة بكيت وليش؟' },
      { q: 'علامة تحذير في نفسك تتجاهلها؟' },
      { q: 'أكثر شي أضعت عليه فلوس وكان غلط؟' },
      { q: 'شي لا زلت تسويه وأنت كبير على عمرك؟' },
      { q: 'شي تتظاهر إنك تحبه بس تكرهه في الحقيقة؟' },
      { q: 'موهبة سرية عندك ما أحد يعلم عنها؟' },
      { q: 'أكثر موقف محرج مريت فيه أمام الناس؟' },
      { q: 'شي تسويه لما تكون لحالك بالكامل ما تعترف فيه؟' },
      { q: 'رأيك الصادق عن أكثر شخص يزعجك في هذي الغرفة؟' },
      { q: 'أسوأ كذبة كذبتها وما انكشفت؟' },
      { q: 'شي تخاف منه بطريقة غير منطقية؟' },
      { q: 'مرحلة مريت فيها تندم عليها؟' },
      { q: 'أتفه خلاف صار معك مؤخراً؟' },
      { q: 'رأيك الحقيقي الصادق في طبخك؟' },
      { q: 'شي سويته تنحرج لو أهلك عرفوا فيه؟' },
      { q: 'أتفه شي سويته للانتقام من أحد؟' },
    ],
  },

  /* ---- DISS TRACK WARS: { p } (prompt about the opponent) ---- */
  diss: {
    en: [
      { p: 'Write a fake WhatsApp status for your opponent' },
      { p: 'Your opponent’s GPS voice would say…' },
      { p: 'The title of your opponent’s autobiography' },
      { p: 'What’s REALLY in your opponent’s search history' },
      { p: 'A one-star review of your opponent' },
      { p: 'Your opponent’s honest LinkedIn headline' },
      { p: 'The warning label printed on your opponent' },
      { p: 'If your opponent was an app, its description would be…' },
      { p: 'Your opponent’s secret talent nobody asked for' },
      { p: 'The ancient prophecy about your opponent' },
      { p: 'Your opponent’s villain origin story in one line' },
      { p: 'What your opponent’s phone would say in therapy' },
      { p: 'Your opponent’s Wikipedia opening line' },
      { p: 'The Netflix show about your opponent: title and description' },
      { p: 'Your opponent’s Yelp review as a human being' },
      { p: 'What your opponent’s parents really think but never say' },
      { p: 'Your opponent’s villain origin story in one sentence' },
      { p: 'Write your opponent\'s Tinder bio' },
      { p: 'A fake news headline about your opponent' },
      { p: 'Your opponent\'s villain speech in one line' },
      { p: 'TripAdvisor review of being your opponent\'s friend' },
      { p: 'Your opponent as a Netflix series: title and tagline' },
      { p: 'What your opponent\'s mom would say about their life choices' },
      { p: 'Your opponent\'s rejected Olympic sport' },
      { p: 'Your opponent\'s dating profile red flags' },
      { p: 'Loading screen tip if your opponent was a video game' },
      { p: 'A motivational quote but about your opponent\'s failures' },
    ],
    ar: [
      { p: 'اكتب حالة واتساب مزيفة لخصمك' },
      { p: '…صوت الملاحة (GPS) عند خصمك بيقول' },
      { p: 'عنوان السيرة الذاتية لخصمك' },
      { p: 'شنو فعلياً في سجل بحث خصمك' },
      { p: 'تقييم نجمة وحدة لخصمك' },
      { p: 'عنوان LinkedIn الصادق لخصمك' },
      { p: 'ملصق التحذير المطبوع على خصمك' },
      { p: '…لو خصمك تطبيق، وصفه بيكون' },
      { p: 'موهبة خصمك السرية اللي محد طلبها' },
      { p: 'النبوءة القديمة عن خصمك' },
      { p: 'قصة تحول خصمك لشرير — بسطر واحد' },
      { p: 'شنو بيقول جوال خصمك عند الطبيب النفسي' },
      { p: 'السطر الأول في ويكيبيديا عن خصمك' },
      { p: 'خصمك كمسلسل نتفليكس: الاسم والوصف' },
      { p: 'تقييم خصمك كإنسان على قوقل' },
      { p: 'شنو أهل خصمك يفكرون فيه بسرّية' },
      { p: 'قصة تحول خصمك لشرير بجملة وحدة' },
      { p: 'اكتب بايو تيندر لخصمك' },
      { p: 'عنوان خبر عاجل زائف عن خصمك' },
      { p: 'خطاب الشرير لخصمك بسطر واحد' },
      { p: 'تقييم TripAdvisor عن الصداقة مع خصمك' },
      { p: 'خصمك كمسلسل نتفليكس: الاسم والوصف' },
      { p: 'شنو أم خصمك بتقول عن اختياراته في الحياة؟' },
      { p: 'الرياضة الأولمبية المرفوضة المناسبة لخصمك' },
      { p: 'علامات التحذير في بروفايل المواعدة لخصمك' },
      { p: 'نصيحة شاشة التحميل لو خصمك كان لعبة فيديو' },
      { p: 'جملة تحفيزية لكنها عن إخفاقات خصمك' },
    ],
  },

  /* ---- MAJLIS QUIZ: { q, options[4], correct(index) } ---- */
  quiz: {
    en: [
      { q: 'Which country has the most islands in the world?', options: ['Indonesia', 'Sweden', 'Philippines', 'Greece'], correct: 1 },
      { q: 'What is the national animal of Oman?', options: ['Falcon', 'Arabian Horse', 'Arabian Oryx', 'Camel'], correct: 2 },
      { q: 'How many strings does a classic oud usually have?', options: ['6', '8', '11', '12'], correct: 2 },
      { q: 'Which planet has the most moons?', options: ['Jupiter', 'Saturn', 'Neptune', 'Mars'], correct: 1 },
      { q: 'The capital of Australia is…', options: ['Sydney', 'Melbourne', 'Canberra', 'Perth'], correct: 2 },
      { q: 'Which sea has no coastline at all?', options: ['Dead Sea', 'Sargasso Sea', 'Caspian Sea', 'Coral Sea'], correct: 1 },
      { q: 'The first Arab country to play in a FIFA World Cup?', options: ['Morocco', 'Saudi Arabia', 'Egypt', 'Tunisia'], correct: 2 },
      { q: 'Omani cuisine is famous for which dried ingredient?', options: ['Dried lime (loomi)', 'Dried figs', 'Dried mint', 'Dried mango'], correct: 0 },
      { q: 'What does “www” stand for?', options: ['World Wide Web', 'Web World Wide', 'Wide World Web', 'World Web Wire'], correct: 0 },
      { q: 'The fastest land animal is…', options: ['Gazelle', 'Cheetah', 'Greyhound', 'Ostrich'], correct: 1 },
      { q: 'Which of these is botanically a berry?', options: ['Strawberry', 'Raspberry', 'Banana', 'Blackberry'], correct: 2 },
      { q: 'The tallest building in the world is in…', options: ['Riyadh', 'Shanghai', 'Dubai', 'Kuala Lumpur'], correct: 2 },
      { q: 'How many bones are in the human body?', options: ['186', '206', '226', '246'], correct: 1 },
      { q: 'Which planet is closest to the Sun?', options: ['Venus', 'Mercury', 'Mars', 'Earth'], correct: 1 },
      { q: 'Most spoken language by native speakers?', options: ['English', 'Spanish', 'Hindi', 'Mandarin'], correct: 3 },
      { q: 'Which country invented pizza?', options: ['France', 'Greece', 'Italy', 'Spain'], correct: 2 },
      { q: 'How many sides does a hexagon have?', options: ['5', '6', '7', '8'], correct: 1 },
      { q: 'Longest bone in the human body?', options: ['Spine', 'Femur', 'Tibia', 'Humerus'], correct: 1 },
      { q: 'Which ocean is the largest?', options: ['Atlantic', 'Indian', 'Arctic', 'Pacific'], correct: 3 },
      { q: 'WWII ended in which year?', options: ['1943', '1944', '1945', '1946'], correct: 2 },
      { q: 'Standard guitar has how many strings?', options: ['4', '5', '6', '7'], correct: 2 },
      { q: 'Element with symbol "Au" is…', options: ['Silver', 'Copper', 'Gold', 'Aluminum'], correct: 2 },
      { q: 'Smallest country in the world?', options: ['Monaco', 'San Marino', 'Vatican City', 'Liechtenstein'], correct: 2 },
      { q: 'Which continent has the most countries?', options: ['Asia', 'Europe', 'Africa', 'Americas'], correct: 2 },
    ],
    ar: [
      { q: 'أي دولة عندها أكبر عدد جزر في العالم؟', options: ['إندونيسيا', 'السويد', 'الفلبين', 'اليونان'], correct: 1 },
      { q: 'شنو الحيوان الوطني لسلطنة عُمان؟', options: ['الصقر', 'الحصان العربي', 'المها العربي', 'الجمل'], correct: 2 },
      { q: 'كم وتر عادةً في العود الكلاسيكي؟', options: ['٦', '٨', '١١', '١٢'], correct: 2 },
      { q: 'أي كوكب عنده أكبر عدد أقمار؟', options: ['المشتري', 'زحل', 'نبتون', 'المريخ'], correct: 1 },
      { q: '…عاصمة أستراليا هي', options: ['سيدني', 'ملبورن', 'كانبرا', 'بيرث'], correct: 2 },
      { q: 'أي بحر ما عنده أي سواحل؟', options: ['البحر الميت', 'بحر سارجاسو', 'بحر قزوين', 'البحر المرجاني'], correct: 1 },
      { q: 'أول دولة عربية تشارك في كأس العالم؟', options: ['المغرب', 'السعودية', 'مصر', 'تونس'], correct: 2 },
      { q: 'المطبخ العماني مشهور بأي مكوّن مجفف؟', options: ['اللومي (الليمون المجفف)', 'التين المجفف', 'النعناع المجفف', 'المانجو المجفف'], correct: 0 },
      { q: 'شنو معنى «www»؟', options: ['World Wide Web', 'Web World Wide', 'Wide World Web', 'World Web Wire'], correct: 0 },
      { q: '…أسرع حيوان بري هو', options: ['الغزال', 'الفهد', 'كلب السلوقي', 'النعامة'], correct: 1 },
      { q: 'أي واحد من هذي يعتبر نباتياً من التوتيات؟', options: ['الفراولة', 'التوت الأحمر', 'الموز', 'التوت الأسود'], correct: 2 },
      { q: '…أطول برج في العالم موجود في', options: ['الرياض', 'شنغهاي', 'دبي', 'كوالالمبور'], correct: 2 },
      { q: 'كم عدد عظام جسم الإنسان؟', options: ['١٨٦', '٢٠٦', '٢٢٦', '٢٤٦'], correct: 1 },
      { q: 'أي كوكب الأقرب للشمس؟', options: ['الزهرة', 'عطارد', 'المريخ', 'الأرض'], correct: 1 },
      { q: 'أكثر لغة متحدث بها كلغة أم في العالم؟', options: ['الإنجليزية', 'الإسبانية', 'الهندية', 'الماندرين'], correct: 3 },
      { q: 'أي دولة اخترعت البيتزا؟', options: ['فرنسا', 'اليونان', 'إيطاليا', 'إسبانيا'], correct: 2 },
      { q: 'كم ضلعاً في السداسي؟', options: ['٥', '٦', '٧', '٨'], correct: 1 },
      { q: 'أطول عظمة في جسم الإنسان؟', options: ['العمود الفقري', 'عظمة الفخذ', 'الساق', 'العضد'], correct: 1 },
      { q: 'أي محيط هو الأكبر؟', options: ['الأطلسي', 'الهندي', 'المتجمد الشمالي', 'الهادي'], correct: 3 },
      { q: 'في أي سنة انتهت الحرب العالمية الثانية؟', options: ['١٩٤٣', '١٩٤٤', '١٩٤٥', '١٩٤٦'], correct: 2 },
      { q: 'كم وتراً في الغيتار العادي؟', options: ['٤', '٥', '٦', '٧'], correct: 2 },
      { q: 'عنصر رمزه Au هو؟', options: ['الفضة', 'النحاس', 'الذهب', 'الألومنيوم'], correct: 2 },
      { q: 'أصغر دولة في العالم؟', options: ['موناكو', 'سان مارينو', 'الفاتيكان', 'ليختنشتاين'], correct: 2 },
      { q: 'أي قارة فيها أكثر عدد من الدول؟', options: ['آسيا', 'أوروبا', 'أفريقيا', 'الأمريكتين'], correct: 2 },
    ],
  },
};

const Content = {
  /* Async so an AI backend can be swapped in with zero changes elsewhere.
     region: 'mena' | 'weur' | 'asia' | 'africa' | null (null = universal only) */
  async get(mode, lang, count, region) {
    // Arab Flavor = use MENA regional pack first; Global Mix = no regional preference
    if (!region) {
      const flavor = window.HYPOX_STATE && window.HYPOX_STATE.flavor;
      region = (flavor === 'arab') ? 'mena' : null;
    }
    const cfg = window.HYPOX_CONFIG || {};
    if (cfg.aiEndpoint) {
      try {
        const res = await fetch(cfg.aiEndpoint, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ mode, lang, count, region }),
        });
        if (res.ok) {
          const data = await res.json();
          if (Array.isArray(data.prompts) && data.prompts.length) return data.prompts.slice(0, count);
        }
      } catch (e) { /* fall through to local packs */ }
    }

    // Guard: nothing to fetch
    if (count <= 0) return [];

    // Warn host if static pool is smaller than requested (content will repeat)
    const poolSize = ((PACKS[mode] && (PACKS[mode][lang] || PACKS[mode].en)) || []).length;
    if (poolSize > 0 && count > poolSize) {
      const toast = document.createElement('div');
      toast.style.cssText = 'position:fixed;bottom:4vmin;left:50%;transform:translateX(-50%);background:#374151;color:#facc15;font-family:Fredoka One,sans-serif;font-size:15px;padding:10px 22px;border-radius:50px;z-index:99;opacity:0.92;pointer-events:none';
      toast.textContent = '🔄 Content repeating — AI backend will fix this';
      document.body.appendChild(toast);
      setTimeout(() => toast.remove(), 3500);
    }



    // Universal pool (always available)
    const universal = (PACKS[mode] && (PACKS[mode][lang] || PACKS[mode].en)) || [];

    // Regional pool for location-sensitive modes (quiz/bluff), if a region is set
    let regional = [];
    if (region && typeof REGION_PACKS !== 'undefined' && REGION_PACKS[region] && REGION_PACKS[region][mode]) {
      regional = REGION_PACKS[region][mode][lang] || REGION_PACKS[region][mode].en || [];
    }

    // Prefer regional first (feels local), then top up from universal so variety stays high.
    const merged = [...shuffle(regional), ...shuffle(universal)];
    // De-dupe by full content
    const seen = new Set(), out = [];
    for (const item of merged) {
      if (out.length >= count) break;
      const key = JSON.stringify(item);
      if (seen.has(key)) continue;
      seen.add(key); out.push(item);
    }
    return out.length ? out : shuffle(universal).slice(0, count);
  },
};

/* ============ TRIVIA CATEGORIES ============
   Used by the "Speed Trivia" mode when a category is selected.
   Each has 12 questions in EN and AR. */
const TRIVIA_CATS = {
  geography: {
    en: [
      { q:'What is the capital of Australia?', options:['Sydney','Melbourne','Canberra','Perth'], correct:2 },
      { q:'Which country has the most natural lakes?', options:['USA','Russia','Canada','Brazil'], correct:2 },
      { q:'The Nile River flows through how many countries?', options:['7','9','11','13'], correct:2 },
      { q:'Which ocean is the largest?', options:['Atlantic','Indian','Arctic','Pacific'], correct:3 },
      { q:'Mount Everest is in which mountain range?', options:['Andes','Alps','Himalayas','Rockies'], correct:2 },
      { q:'What is the smallest country in the world?', options:['Monaco','San Marino','Liechtenstein','Vatican City'], correct:3 },
      { q:'The Amazon River is in which continent?', options:['Africa','Asia','South America','North America'], correct:2 },
      { q:'Which city is both in Europe and Asia?', options:['Moscow','Istanbul','Cairo','Athens'], correct:1 },
      { q:'What is the longest river in the Arab world?', options:['Euphrates','Tigris','Nile','Jordan'], correct:2 },
      { q:'Which country has the most pyramids?', options:['Egypt','Sudan','Mexico','Peru'], correct:1 },
      { q:'The Sahara Desert covers most of which continent?', options:['Asia','Africa','Australia','South America'], correct:1 },
      { q:'Which Gulf country has no river?', options:['Iraq','Kuwait','Oman','Jordan'], correct:1 },
    ],
    ar: [
      { q:'ما عاصمة أستراليا؟', options:['سيدني','ملبورن','كانبرا','بيرث'], correct:2 },
      { q:'أي دولة عندها أكبر عدد بحيرات طبيعية؟', options:['أمريكا','روسيا','كندا','البرازيل'], correct:2 },
      { q:'نهر النيل يمر عبر كم دولة؟', options:['٧','٩','١١','١٣'], correct:2 },
      { q:'أكبر محيط في العالم؟', options:['الأطلسي','الهندي','المتجمد','الهادئ'], correct:3 },
      { q:'جبل إيفرست في أي سلسلة جبلية؟', options:['الأنديز','الألب','الهيمالايا','الروكي'], correct:2 },
      { q:'أصغر دولة في العالم؟', options:['موناكو','سان مارينو','ليختنشتاين','الفاتيكان'], correct:3 },
      { q:'نهر الأمازون في أي قارة؟', options:['أفريقيا','آسيا','أمريكا الجنوبية','أمريكا الشمالية'], correct:2 },
      { q:'أي مدينة في أوروبا وآسيا معاً؟', options:['موسكو','إسطنبول','القاهرة','أثينا'], correct:1 },
      { q:'أطول نهر في العالم العربي؟', options:['الفرات','دجلة','النيل','الأردن'], correct:2 },
      { q:'أي دولة عندها أكبر عدد أهرامات؟', options:['مصر','السودان','المكسيك','بيرو'], correct:1 },
      { q:'الصحراء الكبرى تغطي معظم أي قارة؟', options:['آسيا','أفريقيا','أستراليا','أمريكا'], correct:1 },
      { q:'أي دولة خليجية ليس فيها أنهار؟', options:['العراق','الكويت','عُمان','الأردن'], correct:1 },
    ],
  },
  science: {
    en: [
      { q:'What is the chemical symbol for gold?', options:['Go','Gd','Au','Ag'], correct:2 },
      { q:'How many bones are in the adult human body?', options:['196','206','216','226'], correct:1 },
      { q:'What planet is known as the Red Planet?', options:['Venus','Jupiter','Saturn','Mars'], correct:3 },
      { q:'What is the speed of light (approx)?', options:['200,000 km/s','300,000 km/s','400,000 km/s','500,000 km/s'], correct:1 },
      { q:'DNA stands for?', options:['Deoxyribonucleic Acid','Dioxynuclear Acid','Double Nucleic Arrangement','Digital Nucleic Acid'], correct:0 },
      { q:'What is the hardest natural substance?', options:['Gold','Iron','Diamond','Quartz'], correct:2 },
      { q:'Which gas do plants absorb from the air?', options:['Oxygen','Nitrogen','Carbon Dioxide','Hydrogen'], correct:2 },
      { q:'How many hearts does an octopus have?', options:['1','2','3','4'], correct:2 },
      { q:'What is the powerhouse of the cell?', options:['Nucleus','Ribosome','Mitochondria','Golgi body'], correct:2 },
      { q:'Water boils at what temperature at sea level?', options:['90°C','95°C','100°C','105°C'], correct:2 },
      { q:'Which planet has the most moons?', options:['Jupiter','Saturn','Neptune','Uranus'], correct:1 },
      { q:'What is the most abundant gas in Earth\'s atmosphere?', options:['Oxygen','Argon','Carbon Dioxide','Nitrogen'], correct:3 },
    ],
    ar: [
      { q:'ما الرمز الكيميائي للذهب؟', options:['Go','Gd','Au','Ag'], correct:2 },
      { q:'كم عظمة في جسم الإنسان البالغ؟', options:['١٩٦','٢٠٦','٢١٦','٢٢٦'], correct:1 },
      { q:'أي كوكب يُعرف بالكوكب الأحمر؟', options:['الزهرة','المشتري','زحل','المريخ'], correct:3 },
      { q:'ما سرعة الضوء تقريباً؟', options:['٢٠٠ ألف كم/ث','٣٠٠ ألف كم/ث','٤٠٠ ألف كم/ث','٥٠٠ ألف كم/ث'], correct:1 },
      { q:'DNA اختصار لـ؟', options:['حمض الديوكسي ريبونيوكليك','حمض نووي مزدوج','حمض نيتروجيني','حمض ريبوزي'], correct:0 },
      { q:'أصلب مادة طبيعية؟', options:['الذهب','الحديد','الماس','الكوارتز'], correct:2 },
      { q:'أي غاز تمتصه النباتات من الهواء؟', options:['الأكسجين','النيتروجين','ثاني أكسيد الكربون','الهيدروجين'], correct:2 },
      { q:'كم قلب عند الأخطبوط؟', options:['١','٢','٣','٤'], correct:2 },
      { q:'محطة الطاقة في الخلية؟', options:['النواة','الريبوسوم','الميتوكوندريا','جهاز غولجي'], correct:2 },
      { q:'الماء يغلي على كم درجة عند مستوى البحر؟', options:['٩٠','٩٥','١٠٠','١٠٥'], correct:2 },
      { q:'أي كوكب عنده أكثر أقمار؟', options:['المشتري','زحل','نبتون','أورانوس'], correct:1 },
      { q:'أكثر غاز في الغلاف الجوي للأرض؟', options:['الأكسجين','الأرغون','ثاني أكسيد الكربون','النيتروجين'], correct:3 },
    ],
  },
  gulf: {
    en: [
      { q:'What is the tallest building in the world?', options:['Burj Al Arab','Kingdom Tower','Burj Khalifa','ADNOC HQ'], correct:2 },
      { q:'Which Gulf country produces the most oil?', options:['UAE','Kuwait','Qatar','Saudi Arabia'], correct:3 },
      { q:'What is the national dish of Saudi Arabia?', options:['Kabsa','Harees','Mandi','Jareesh'], correct:0 },
      { q:'The GCC was founded in which year?', options:['1975','1981','1985','1990'], correct:1 },
      { q:'Which emirate in the UAE is the largest by area?', options:['Dubai','Sharjah','Abu Dhabi','Ras Al Khaimah'], correct:2 },
      { q:'What does "Wasta" mean in Gulf culture?', options:['A type of food','Using connections/influence','A traditional dance','A form of greeting'], correct:1 },
      { q:'The Pearl Roundabout was in which country?', options:['Kuwait','Bahrain','Qatar','UAE'], correct:1 },
      { q:'Which country has the tallest flagpole in the Arab world?', options:['Saudi Arabia','Jordan','Egypt','UAE'], correct:1 },
      { q:'Karak tea is most associated with which country?', options:['India','Pakistan','Kuwait','Qatar'], correct:2 },
      { q:'What is the official currency of Oman?', options:['Dirham','Riyal','Dinar','Dollar'], correct:1 },
      { q:'Which Gulf city is known as the "City of Gold"?', options:['Riyadh','Abu Dhabi','Dubai','Doha'], correct:2 },
      { q:'What sport is the UAE\'s national sport?', options:['Football','Camel Racing','Falconry','Horse Racing'], correct:2 },
    ],
    ar: [
      { q:'أطول مبنى في العالم؟', options:['برج العرب','برج المملكة','برج خليفة','مقر أدنوك'], correct:2 },
      { q:'أي دولة خليجية تنتج أكثر نفط؟', options:['الإمارات','الكويت','قطر','السعودية'], correct:3 },
      { q:'الطبق الوطني للسعودية؟', options:['الكبسة','الهريس','المندي','الجريش'], correct:0 },
      { q:'مجلس التعاون الخليجي أُسس في أي سنة؟', options:['١٩٧٥','١٩٨١','١٩٨٥','١٩٩٠'], correct:1 },
      { q:'أكبر إمارة في الإمارات مساحةً؟', options:['دبي','الشارقة','أبوظبي','رأس الخيمة'], correct:2 },
      { q:'معنى "الواسطة" في الثقافة الخليجية؟', options:['نوع أكل','استخدام العلاقات','رقصة تراثية','طريقة تحية'], correct:1 },
      { q:'دوار اللؤلؤة كان في أي دولة؟', options:['الكويت','البحرين','قطر','الإمارات'], correct:1 },
      { q:'أطول سارية علم في العالم العربي؟', options:['السعودية','الأردن','مصر','الإمارات'], correct:1 },
      { q:'شاي الكرك مرتبط أكثر بأي دولة؟', options:['الهند','باكستان','الكويت','قطر'], correct:2 },
      { q:'عملة سلطنة عُمان الرسمية؟', options:['الدرهم','الريال','الدينار','الدولار'], correct:1 },
      { q:'أي مدينة خليجية تُعرف بـ"مدينة الذهب"؟', options:['الرياض','أبوظبي','دبي','الدوحة'], correct:2 },
      { q:'الرياضة الوطنية للإمارات؟', options:['الكرة','سباق الجِمال','الصيد بالصقر','سباق الخيل'], correct:2 },
    ],
  },
  pop: {
    en: [
      { q:'Which app has the most monthly active users?', options:['Instagram','TikTok','YouTube','WhatsApp'], correct:3 },
      { q:'Who sang "Shape of You"?', options:['Justin Bieber','Bruno Mars','Ed Sheeran','Harry Styles'], correct:2 },
      { q:'Netflix was founded in which year?', options:['1997','1999','2001','2003'], correct:0 },
      { q:'What does "LOL" stand for?', options:['Lots of Love','Laugh Out Loud','League of Legends','All of the above'], correct:3 },
      { q:'Which country produces the most movies per year?', options:['USA','Nigeria','India','China'], correct:2 },
      { q:'The iPhone was first released in?', options:['2005','2006','2007','2008'], correct:2 },
      { q:'Who is the most followed person on Instagram?', options:['Cristiano Ronaldo','Kylie Jenner','Selena Gomez','Leo Messi'], correct:0 },
      { q:'Which game has the most players ever?', options:['Fortnite','Minecraft','PUBG','GTA V'], correct:1 },
      { q:'What is the most streamed song on Spotify ever?', options:['Blinding Lights','Shape of You','Bohemian Rhapsody','Despacito'], correct:0 },
      { q:'TikTok is owned by which company?', options:['Tencent','Alibaba','ByteDance','Baidu'], correct:2 },
      { q:'Which show has the most Emmy wins?', options:['Breaking Bad','Game of Thrones','The Wire','Succession'], correct:1 },
      { q:'What year did COVID-19 officially become a pandemic?', options:['2019','2020','2021','2022'], correct:1 },
    ],
    ar: [
      { q:'أي تطبيق عنده أكثر مستخدمين شهرياً؟', options:['انستقرام','تيك توك','يوتيوب','واتساب'], correct:3 },
      { q:'منو غنى "Shape of You"؟', options:['جاستن بيبر','برونو مارس','إد شيران','هاري ستايلز'], correct:2 },
      { q:'نتفليكس أُسست في أي سنة؟', options:['١٩٩٧','١٩٩٩','٢٠٠١','٢٠٠٣'], correct:0 },
      { q:'شنو معنى "LOL"؟', options:['كثير من الحب','اضحك بصوت عالي','ليغ أوف ليجندز','كل ما سبق'], correct:3 },
      { q:'أي دولة تنتج أكثر أفلام سنوياً؟', options:['أمريكا','نيجيريا','الهند','الصين'], correct:2 },
      { q:'أول آيفون نزل في؟', options:['٢٠٠٥','٢٠٠٦','٢٠٠٧','٢٠٠٨'], correct:2 },
      { q:'أكثر شخص متابَع على انستقرام؟', options:['رونالدو','كايلي جينر','سيلينا غوميز','ميسي'], correct:0 },
      { q:'أي لعبة عندها أكثر لاعبين؟', options:['فورتنايت','ماينكرافت','ببجي','GTA V'], correct:1 },
      { q:'أكثر أغنية استمعت على سبوتيفاي؟', options:['Blinding Lights','Shape of You','Bohemian Rhapsody','Despacito'], correct:0 },
      { q:'تيك توك ملك أي شركة؟', options:['تينسنت','علي بابا','بايت دانس','بايدو'], correct:2 },
      { q:'أي مسلسل ربح أكثر جائزة إيمي؟', options:['Breaking Bad','Game of Thrones','The Wire','Succession'], correct:1 },
      { q:'كوفيد-١٩ أصبح رسمياً وباءً في أي سنة؟', options:['٢٠١٩','٢٠٢٠','٢٠٢١','٢٠٢٢'], correct:1 },
    ],
  },
  sports: {
    en: [
      { q:'How many players are on a football (soccer) team?', options:['9','10','11','12'], correct:2 },
      { q:'Which country has won the most FIFA World Cups?', options:['Germany','Argentina','Italy','Brazil'], correct:3 },
      { q:'The 2022 World Cup was held in?', options:['UAE','Saudi Arabia','Qatar','Kuwait'], correct:2 },
      { q:'How many Grand Slam tournaments are in tennis?', options:['2','3','4','5'], correct:2 },
      { q:'Michael Jordan played for which NBA team?', options:['Lakers','Celtics','Bulls','Heat'], correct:2 },
      { q:'How many rings are on the Olympic flag?', options:['4','5','6','7'], correct:1 },
      { q:'Which country invented football (soccer)?', options:['Brazil','Spain','England','Italy'], correct:2 },
      { q:'How long is a standard marathon?', options:['40km','42.195km','44km','45km'], correct:1 },
      { q:'In which sport do you use a shuttlecock?', options:['Tennis','Squash','Badminton','Racquetball'], correct:2 },
      { q:'Cristiano Ronaldo plays for which country?', options:['Spain','Brazil','Portugal','Italy'], correct:2 },
      { q:'Which city hosted the 2024 Summer Olympics?', options:['Los Angeles','Tokyo','London','Paris'], correct:3 },
      { q:'How many players are on a basketball team on court?', options:['4','5','6','7'], correct:1 },
    ],
    ar: [
      { q:'كم لاعب في فريق كرة القدم؟', options:['٩','١٠','١١','١٢'], correct:2 },
      { q:'أي دولة فازت بأكثر كؤوس عالم؟', options:['ألمانيا','الأرجنتين','إيطاليا','البرازيل'], correct:3 },
      { q:'كأس العالم ٢٠٢٢ انعقد في؟', options:['الإمارات','السعودية','قطر','الكويت'], correct:2 },
      { q:'كم بطولة غراند سلام في التنس؟', options:['٢','٣','٤','٥'], correct:2 },
      { q:'مايكل جوردان لعب مع أي فريق NBA؟', options:['ليكرز','سيلتيكس','بولز','هيت'], correct:2 },
      { q:'كم حلقة على علم الأولمبياد؟', options:['٤','٥','٦','٧'], correct:1 },
      { q:'أي دولة اخترعت كرة القدم؟', options:['البرازيل','إسبانيا','إنجلترا','إيطاليا'], correct:2 },
      { q:'طول سباق الماراثون القياسي؟', options:['٤٠كم','٤٢.١٩٥كم','٤٤كم','٤٥كم'], correct:1 },
      { q:'في أي رياضة تستخدم الريشة؟', options:['التنس','السكواش','البادمنتون','الراكيتبول'], correct:2 },
      { q:'رونالدو يلعب لأي منتخب؟', options:['إسبانيا','البرازيل','البرتغال','إيطاليا'], correct:2 },
      { q:'أي مدينة استضافت أولمبياد صيف ٢٠٢٤؟', options:['لوس أنجلوس','طوكيو','لندن','باريس'], correct:3 },
      { q:'كم لاعب في الملعب في كرة السلة؟', options:['٤','٥','٦','٧'], correct:1 },
    ],
  },
};

/* ============ PINPOINT — geography guessing (PinWorld style) ============ */
const PINPOINT_CITIES = [
  { en:'Dubai', ar:'دبي', lat:25.2, lon:55.3 },
  { en:'Paris', ar:'باريس', lat:48.9, lon:2.35 },
  { en:'Tokyo', ar:'طوكيو', lat:35.7, lon:139.7 },
  { en:'New York', ar:'نيويورك', lat:40.7, lon:-74.0 },
  { en:'Cairo', ar:'القاهرة', lat:30.0, lon:31.2 },
  { en:'London', ar:'لندن', lat:51.5, lon:-0.13 },
  { en:'Muscat', ar:'مسقط', lat:23.6, lon:58.5 },
  { en:'Rio de Janeiro', ar:'ريو دي جانيرو', lat:-22.9, lon:-43.2 },
  { en:'Sydney', ar:'سيدني', lat:-33.9, lon:151.2 },
  { en:'Moscow', ar:'موسكو', lat:55.8, lon:37.6 },
  { en:'Cape Town', ar:'كيب تاون', lat:-33.9, lon:18.4 },
  { en:'Mumbai', ar:'مومباي', lat:19.1, lon:72.9 },
  { en:'Istanbul', ar:'إسطنبول', lat:41.0, lon:29.0 },
  { en:'Mexico City', ar:'مكسيكو سيتي', lat:19.4, lon:-99.1 },
  { en:'Riyadh', ar:'الرياض', lat:24.7, lon:46.7 },
  { en:'Singapore', ar:'سنغافورة', lat:1.35, lon:103.8 },
  { en:'Reykjavik', ar:'ريكيافيك', lat:64.1, lon:-21.9 },
  { en:'Nairobi', ar:'نيروبي', lat:-1.3, lon:36.8 },
  { en:'Buenos Aires', ar:'بوينس آيرس', lat:-34.6, lon:-58.4 },
  { en:'Seoul', ar:'سيول', lat:37.6, lon:127.0 },
  { en:'Doha', ar:'الدوحة', lat:25.3, lon:51.5 },
  { en:'Los Angeles', ar:'لوس أنجلوس', lat:34.05, lon:-118.2 },
  { en:'Rome', ar:'روما', lat:41.9, lon:12.5 },
  { en:'Bangkok', ar:'بانكوك', lat:13.75, lon:100.5 },
];

/* ===== EMOJI RIDDLE pack ===== */
PACKS.emoji = {
  en: [
    { e:'🗼🥐🍷', options:['Paris','Rome','London','Madrid'], correct:0 },
    { e:'🕌🐪🛢️', options:['Saudi Arabia','Morocco','Turkey','Iran'], correct:0 },
    { e:'🍕🏛️🛵', options:['Rome','Athens','Barcelona','Lisbon'], correct:0 },
    { e:'🗽🍔🚕', options:['New York','Chicago','Los Angeles','Toronto'], correct:0 },
    { e:'🍣🗻🚄', options:['Tokyo','Seoul','Beijing','Bangkok'], correct:0 },
    { e:'🏙️🛍️🏎️', options:['Dubai','Doha','Riyadh','Kuwait City'], correct:0 },
    { e:'🐨🏄☀️', options:['Australia','South Africa','Brazil','Hawaii'], correct:0 },
    { e:'🍫⌚🏔️', options:['Switzerland','Austria','Norway','Belgium'], correct:0 },
    { e:'🐫🔺🏺', options:['Egypt','Jordan','Tunisia','Sudan'], correct:0 },
    { e:'🌷🚲🧀', options:['Netherlands','Denmark','Belgium','Germany'], correct:0 },
    { e:'🫖👑☔', options:['London','Dublin','Edinburgh','Amsterdam'], correct:0 },
    { e:'🌮🌶️🎸', options:['Mexico','Spain','Colombia','Peru'], correct:0 },
    { e:'🍁🏒🐻', options:['Canada','Russia','Finland','Sweden'], correct:0 },
    { e:'🏰🍺🚗', options:['Germany','Czechia','Poland','Austria'], correct:0 },
    { e:'⚽🎭🏖️', options:['Rio de Janeiro','Buenos Aires','Lisbon','Miami'], correct:0 },
    { e:'🌋🧊♨️', options:['Iceland','Greenland','New Zealand','Chile'], correct:0 },
  ],
  ar: [
    { e:'🗼🥐🍷', options:['باريس','روما','لندن','مدريد'], correct:0 },
    { e:'🕌🐪🛢️', options:['السعودية','المغرب','تركيا','إيران'], correct:0 },
    { e:'🍕🏛️🛵', options:['روما','أثينا','برشلونة','لشبونة'], correct:0 },
    { e:'🗽🍔🚕', options:['نيويورك','شيكاغو','لوس أنجلوس','تورونتو'], correct:0 },
    { e:'🍣🗻🚄', options:['طوكيو','سيول','بكين','بانكوك'], correct:0 },
    { e:'🏙️🛍️🏎️', options:['دبي','الدوحة','الرياض','الكويت'], correct:0 },
    { e:'🐨🏄☀️', options:['أستراليا','جنوب أفريقيا','البرازيل','هاواي'], correct:0 },
    { e:'🍫⌚🏔️', options:['سويسرا','النمسا','النرويج','بلجيكا'], correct:0 },
    { e:'🐫🔺🏺', options:['مصر','الأردن','تونس','السودان'], correct:0 },
    { e:'🌷🚲🧀', options:['هولندا','الدنمارك','بلجيكا','ألمانيا'], correct:0 },
    { e:'🫖👑☔', options:['لندن','دبلن','إدنبرة','أمستردام'], correct:0 },
    { e:'🌮🌶️🎸', options:['المكسيك','إسبانيا','كولومبيا','بيرو'], correct:0 },
    { e:'🍁🏒🐻', options:['كندا','روسيا','فنلندا','السويد'], correct:0 },
    { e:'🏰🍺🚗', options:['ألمانيا','التشيك','بولندا','النمسا'], correct:0 },
    { e:'⚽🎭🏖️', options:['ريو دي جانيرو','بوينس آيرس','لشبونة','ميامي'], correct:0 },
    { e:'🌋🧊♨️', options:['آيسلندا','جرينلاند','نيوزيلندا','تشيلي'], correct:0 },
  ],
};

/* ===== TIME MACHINE pack ===== */
PACKS.year = {
  en: [
    { q:'The first iPhone was released', y:2007 },
    { q:'Man first walked on the Moon', y:1969 },
    { q:'The Titanic sank', y:1912 },
    { q:'Burj Khalifa officially opened', y:2010 },
    { q:'The FIFA World Cup was held in Qatar', y:2022 },
    { q:'Facebook was founded', y:2004 },
    { q:'The Berlin Wall fell', y:1989 },
    { q:'The first Harry Potter book was published', y:1997 },
    { q:'YouTube was launched', y:2005 },
    { q:'Sultan Qaboos began his reign in Oman', y:1970 },
    { q:'The UAE was founded', y:1971 },
    { q:'WhatsApp was launched', y:2009 },
    { q:'The first FIFA World Cup was played', y:1930 },
    { q:'Google was founded', y:1998 },
  ],
  ar: [
    { q:'صدر أول آيفون', y:2007 },
    { q:'أول هبوط للإنسان على القمر', y:1969 },
    { q:'غرقت سفينة التايتنك', y:1912 },
    { q:'افتتح برج خليفة رسمياً', y:2010 },
    { q:'أقيم كأس العالم في قطر', y:2022 },
    { q:'تأسس فيسبوك', y:2004 },
    { q:'سقط جدار برلين', y:1989 },
    { q:'صدر أول كتاب هاري بوتر', y:1997 },
    { q:'انطلق يوتيوب', y:2005 },
    { q:'تولى السلطان قابوس الحكم في عمان', y:1970 },
    { q:'تأسست دولة الإمارات', y:1971 },
    { q:'انطلق واتساب', y:2009 },
    { q:'أقيم أول كأس عالم لكرة القدم', y:1930 },
    { q:'تأسست جوجل', y:1998 },
  ],
};

/* ===== PINPOINT landmarks with photos (Wikimedia) ===== */
const WM = f => 'https://commons.wikimedia.org/wiki/Special:FilePath/' + f + '?width=900';
const PINPOINT_PLACES = [
  { en:'Eiffel Tower', ar:'برج إيفل', lat:48.858, lon:2.294, img:WM('Tour_Eiffel_Wikimedia_Commons.jpg') },
  { en:'Petra', ar:'البتراء', lat:30.329, lon:35.444, img:WM('Al_Khazneh_Petra_edit_2.jpg') },
  { en:'Machu Picchu', ar:'ماتشو بيتشو', lat:-13.163, lon:-72.545, img:WM('Machu_Picchu,_Peru.jpg') },
  { en:'Pyramids of Giza', ar:'أهرامات الجيزة', lat:29.979, lon:31.134, img:WM('Kheops-Pyramid.jpg') },
  { en:'Taj Mahal', ar:'تاج محل', lat:27.175, lon:78.042, img:WM('Taj_Mahal_(Edited).jpeg') },
  { en:'Statue of Liberty', ar:'تمثال الحرية', lat:40.689, lon:-74.045, img:WM('Statue_of_Liberty_7.jpg') },
  { en:'Colosseum', ar:'الكولوسيوم', lat:41.890, lon:12.492, img:WM('Colosseo_2020.jpg') },
  { en:'Burj Khalifa', ar:'برج خليفة', lat:25.197, lon:55.274, img:WM('Burj_Khalifa.jpg') },
  { en:'Great Wall of China', ar:'سور الصين العظيم', lat:40.432, lon:116.570, img:WM('The_Great_Wall_of_China_at_Jinshanling-edit.jpg') },
  { en:'Sydney Opera House', ar:'دار أوبرا سيدني', lat:-33.857, lon:151.215, img:WM('Sydney_Opera_House_-_Dec_2008.jpg') },
  { en:'Christ the Redeemer', ar:'تمثال المسيح الفادي', lat:-22.952, lon:-43.210, img:WM('Christ_the_Redeemer_-_Cristo_Redentor.jpg') },
  { en:'Golden Gate Bridge', ar:'جسر البوابة الذهبية', lat:37.820, lon:-122.478, img:WM('GoldenGateBridge-001.jpg') },
];
